### ISSUE TITLE
[Feature Request] meta channels

### ISSUE THREAD

**Issue by f242** [kotatogram/kotatogram-desktop#10]
когда много каналов на одну тему, то не удобно скакать по ним и читать и вот было бы удобно, чтобы самому создать локальный мета-канал в котором отображались бы посты из выбранных каналов, выглядело бы это как групповой чат, только вместо участников юзерпики каналов и сообщения из них, оригинальные каналы чтобы не занимать список чатов можно было бы в архив поместить

**Comment by RadRussianRus** [comment]
Насколько я помню, ленты каналов хотели сделать, но потом отказались от этой идеи. В TDesktop остался кусок, связанный конкретно с лентами, но вопрос, будет ли он работать сам по себе.

В любом случае, я на этот счёт тоже планировал посмотреть, но когда до конкретно этого доберусь, сказать точно не могу.

**Comment by f242** [comment]
ну в планах есть и хорошо, не мне одному этого не хватает значит)
