### ISSUE TITLE
[Feature Request] Исключить из поиска чаты, которые в архиве

### ISSUE THREAD

**Issue by Neurotoxin001** [kotatogram/kotatogram-desktop#100]
### Is your feature request related to a problem?
Бывает нужно найти определённую новость, но если ты состоишь в множестве чатов, то найти эту самую новость исключительно в каналах практически невозможно, при этом чаты находятся в архиве, а каналы - нет

**Comment by RadRussianRus** [comment]
Эта неочевидная функция уже есть в официальном клиенте: правый клик по любому найденному сообщению.
![](https://user-images.githubusercontent.com/2903496/92547574-d5bc7700-f25d-11ea-89ea-616edfc2d400.png)
