### ISSUE TITLE
[Feature Request] Support for scaling UI lower then 100%

### ISSUE THREAD

**Issue by TomTheDragon** [kotatogram/kotatogram-desktop#103]
### Is your feature request related to a problem?
The UI takes up too much space on low-res screens (<=720p)

### Describe the solution you'd like
The abbility to turn down the UI scaling lower then 100%

### Additional context
I already turned down the scale on pretty much everything at my Linux distro and it does work great so far. But (as far as i know) there is no way to scale down Kotatogram, without a modification to the code

**Comment by RadRussianRus** [comment]
TDesktop already supports scales down to 75%. Just add `-scale 75` to start parameter, where `75` is scale in percentage from 75 to 300.

You can use JSON option `scales` to set up to 6 custom scale values in Settings menu. For example:
```json
{
    "...": "...",
    "scales": [75, 90, 100, 120, 150],
    "...": "..."
}
```
will make scales in settings look like this:
![](https://user-images.githubusercontent.com/2903496/93051272-e198a680-f66c-11ea-8155-5016b0c7923e.png)

**Comment by TomTheDragon** [comment]
Ah thanks, it works great on Win10 and Mint20! :)
Too bad that its kind of hidden like that, since its a very usefull feature :/
