### ISSUE TITLE
[Feature Request] Local ignore function for groups and private chats

### ISSUE THREAD

**Issue by TomTheDragon** [kotatogram/kotatogram-desktop#108]
### Is your feature request related to a problem?
In the current state of Telegram, its not possible to ignore (not block) users inside groups or private chats.

### Describe the solution you'd like
A button (or similar) to just ignore certain users localy, so that incoming messages just get ignored.

### Describe alternatives you've considered
A block/ignore function "just" for groups, since its more important.

**Comment by ilya-fedin** [comment]
Duplicate of #17
