### ISSUE TITLE
Problem With Anti-Virus

### ISSUE THREAD

**Issue by lonelyglitch** [kotatogram/kotatogram-desktop#109]
BitDefender Antivirus and it's engine report Kotatogram as a threat and keep trying to delete it from the device.

![Screenshot 2020-09-28 101515](https://user-images.githubusercontent.com/68129241/94399160-bc7b5c00-0173-11eb-9561-011f7a22ed03.jpg)

**Comment by ilya-fedin** [comment]
#80

**Comment by RadRussianRus** [comment]
False positive. I have no idea what counts as malware.
For now you can just add it to exceptions.
