### ISSUE TITLE
[Feature Request] Multi Account Support

### ISSUE THREAD

**Issue by Azhe403** [kotatogram/kotatogram-desktop#11]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Multi Account like Telegram for Android

### Describe alternatives you've considered
Currently I use multiple Telegram portable executable to login for many account.

### Additional context
N/A

**Comment by VaGNaroK** [comment]
> ### Is your feature request related to a problem?
> 
> No
> ### Describe the solution you'd like
> 
> Multi Account like Telegram for Android
> ### Describe alternatives you've considered
> 
> Currently I use multiple Telegram portable executable to login for many account.
> ### Additional context
> 
> N/A

since the official clients and forks do not have multiple accounts function I solved my problem by installing the official client (using one account) and the kotatogram (in another account) all in flatpak (since they work in containers and there is no conflict between them) .

**Comment by RadRussianRus** [comment]
You can use `-workdir` option for now.

**Comment by RadRussianRus** [comment]
Multi-account is now available in TDesktop beta 2.1.14+ and Kotatogram beta 1.3.7+.
