### ISSUE TITLE
Freeze when clicking the "add attachment"-button

### ISSUE THREAD

**Issue by NitroNils** [kotatogram/kotatogram-desktop#113]
### Steps to reproduce
1. Click button to add a file to chat 

### Expected behaviour
I expected to get a native file-picker.

### Actual behaviour
App freezes. I think the cursor keeps blinking, but everything else in program is frozen. Links are not clickable, cannot write anything, cannot open/change groups/chats, etc.

### Configuration
**Operating system:**
    Linux Mint 20

**Version of Telegram Desktop:**
    1.3.5
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
    Don't remember - yes - the native Flatpak integration, via the Software Manager (Default method). (That might explain its sluggishness.)
**Used theme**:
    Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
    - Don't know where to find logs.
</details>

Thank you!

**Comment by ilya-fedin** [comment]
flatpaks use xdg-desktop-portal to show file dialog, if it doesn't present or there's no backends (one of xdg-desktop-portal-{gtk,kde}) installed, then Qt apps (not sure about gtk ones, maybe gtk has a fallback) will just hang.

**Comment by NitroNils** [comment]
"xdg-desktop-portal-gtk is already the newest version (1.6.0-1build1)"

**Comment by ilya-fedin** [comment]
What about the frontend, xdg-desktop-portal?

**Comment by ilya-fedin** [comment]
> Should the app tell the user that, rather than hang?

App even doesn't know anything about that, this is handled internally in Qt

**Comment by NitroNils** [comment]
"xdg-desktop-portal is already the newest version (1.6.0-1)."

Oh, I see.

**Comment by ilya-fedin** [comment]
> "xdg-desktop-portal is already the newest version (1.6.0-1)."

Try to call this
`busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.FileChooser OpenFile "ssa{sv}" "" "" 0`

> Maybe it'd be easier if I build/installed from source?

I don't think so, official Telegram building instructions are only for Ubuntu 14.04 and won't work with any other Ubuntu versions due to hardcoded paths and library versions, so you will should install it.

There are a community-maintained packaged way of building, but doesn't work on Debian and its dervatives due to the fact that their maintainers stripping private qtwayland headers.

**Comment by NitroNils** [comment]
```busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.FileChooser OpenFile "ssa{sv}" "" "" 0```

```Failed to set address: No such file or directory```

OK

**Comment by ilya-fedin** [comment]
> OK

So this issue could be closed?

**Comment by NitroNils** [comment]
Sorry, I went to GhostBSD and it comes w/ the official client.
Wait, I still have the laptop and could follow up if needed?

**Comment by ilya-fedin** [comment]
> Wait, I still have the laptop and could follow up if needed?

Don't understand that part

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
