### ISSUE TITLE
[Question]  MtProxy doens't work

### ISSUE THREAD

**Issue by MMahdiZojajiM** [kotatogram/kotatogram-desktop#114]
Why proxy(mtproto) works fine in telegram desktop but it doesn't work in kotato?
is it a bug?

**Comment by RadRussianRus** [comment]
I haven't touched proxies, so it should be same as in TDesktop. Can you share this info:
* Kotatogram version
* Telegram Desktop version

Also it would be useful if you can share MTProxy you are testing with.

**Comment by MrMahdi313** [comment]
Kotatogram version is: 1.3.5
and tdesktop version: 2.4.7
and please send message in telegram to send proxy to you.
my telegram username:
@Mr_Mahdi313

**Comment by RadRussianRus** [comment]
Can you check it on [Kotatogram 1.3.9 beta](https://github.com/kotatogram/kotatogram-desktop/releases/tag/k1.3.9)? 1.3.5 uses TD 2.1.4 sources, so maybe that's the problem here.

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
