### ISSUE TITLE
Size font

### ISSUE THREAD

**Issue by mamutal91** [kotatogram/kotatogram-desktop#123]
I met this client today and I'm really enjoying it.
I use Linux with i3-wm, and one thing I really miss is being able to resize the font size.
If you ever do that, I will be grateful.

**Comment by ilya-fedin** [comment]
This would be really hard to do since tdesktop uses custom edited copy of QText from Qt 5.6 with hardcoded values for text rendering due to pixmap emoji support.

**Comment by RadRussianRus** [comment]
There is a possiblity to make at least some predefined font sizes, but I can't say when.

**Comment by RadRussianRus** [comment]
I think it's solved by #177 currently, so at least JSON option will be shipped with next release.
