### ISSUE TITLE
[Question] RAM usage

### ISSUE THREAD

**Issue by MangaD** [kotatogram/kotatogram-desktop#135]
I have just installed Kotatogram on Arch linux, but it is consuming 420 MiB RAM. Is there any way that I can decrease the memory consumption of this program?

**Comment by ilya-fedin** [comment]
No, kotatogram has the same memory leaks as tdesktop

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
