### ISSUE TITLE
Compatibility with latest Telegram

### ISSUE THREAD

**Issue by gjf** [kotatogram/kotatogram-desktop#142]
Is there any possibility to make profile compatible with latest official Telegram Desktop?
As far as I understand there is a conflict because of multiuser concept of Kotatogram (more accounts) - but possible it could be fixed with no influence on features?

**Comment by ilya-fedin** [comment]
We just modified a constant to allow more accounts
https://github.com/kotatogram/kotatogram-desktop/blob/7260b059006183800dfd12b34d463cfd79a1badd/Telegram/SourceFiles/main/main_domain.h#L35-L39

I don't understand what do you want from us to do...

**Comment by gjf** [comment]
Just to undersatnd what do I mean.
From some time I prefer to use two clients: official one (because it updates rapidly) and Kotatogram (because it has some advanced features). Too bad there is nothing that combines them both.
I have created a small tool that allows to start and choose which client to run. And 6-8 months ago bot Kotatogram and Telegram can work with the same tdata folder that contains profiles (and about 1-2 years ago even obsolete Telegreat could work with the same tdata also).
But not now. Actually Kotatpgram starts with Telegram tdata - but telegram cannot run tdata afterwards exiting with crash.

So my question: is it possible to restore back compatibility?

To reproduce the crash you can do the following:

1. Put both Telegram and Kotatogram portable clients in one folder.
2. Start Kotatogram. 
3. Add 4 profiles (my case).
4. Close Kotatogram, start Telegram.
5. It will crash.

Actually you can do it vice versa - create profiles with Telegram and start Kotatogram afterwards. In my case - it worked, but you can never return back to official client.

**Comment by gjf** [comment]
In fact you can check the idea I am using in this repo: https://github.com/gjf/TgMP

**Comment by RadRussianRus** [comment]
There is no reason to have it compatible with older versions, since new versions usually introduce major changes and incompatibilities, and supporting it will be a headache.

I can only suggest you to create a separate profile directory and use it with `-workdir /path/to/your/profile/folder`.

**Comment by RadRussianRus** [comment]
> In fact you can check the idea I am using in this repo: https://github.com/gjf/TgMP

I think I saw that script earlier. But it's really an unsafe way of multi-instancing. With `-workdir` you can be at least sure that even if your app is updated, you can use old profile in old app.

**Comment by RadRussianRus** [comment]
That was unintentional, sorry.

**Comment by ilya-fedin** [comment]
> So my question: is it possible to restore back compatibility?

There are a dumb assert: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/main/main_domain.cpp#L239

**Comment by ilya-fedin** [comment]
Looks like this requires writing a custom separate storage for account. This is a lot of work and I don't see any point personally. IMHO, this is worth to state as "we won't work on it, but we accept a PR if someone implement this".

**Comment by gjf** [comment]
Guys, don't be to aggressive, it was just a question! :)
Now I clearly see the only way is to create different profiles for different clients (with implementing -workdir of course).
The only problem is size - profiles are quite huge. And packing them is not the option as it consumes to much time.
Anyway - thanks for your replies!

**Comment by ilya-fedin** [comment]
> Guys, don't be to aggressive, it was just a question! :)

We're not aggresive, we're just not native speakers ¯\_(ツ)_/¯

**Comment by gjf** [comment]
Ну так бы сразу и писали )

**Comment by gjf** [comment]
Ну тогда на чисто русском: иметь кучу профилей для разных клиентов - это просто пипец с точки зрения места на диске (потому как речь о портативках).
И параметр -workdir сделан криво, потому как рассматривается рабочая папка, в которой должен быть этот самый tdata. Сам tdata не выкорчевать. Итого - ещё один уровень папок, вообще песня с учётом виндозных ограничений на количество символов в пути.

**Comment by ilya-fedin** [comment]
Ну слушай, тут слишком дофига делать, у этого файла кастомный бинарный формат с шифрованием. Если сам запилишь PR - пожалуйста, но вряд ли кто-то будет из нас такое делать...

**Comment by gjf** [comment]
Да я проще запилю батник, в котором будут папки с профилями, в каждом - подпапка с именем клиента и tdata в каждом отдельно.

**Comment by RadRussianRus** [comment]
> Ну тогда на чисто русском: иметь кучу профилей для разных клиентов - это просто пипец с точки зрения места на диске (потому как речь о портативках).

Увы, тут только ставить, чтобы чистилось почаще. Но хотя бы есть гарантия, что при обновлении одного клиента на другом ничего не слетит.

> И параметр -workdir сделан криво, потому как рассматривается рабочая папка, в которой должен быть этот самый tdata. Сам tdata не выкорчевать. Итого - ещё один уровень папок, вообще песня с учётом виндозных ограничений на количество символов в пути.

Рабочая папка используется также для log.txt и папки DebugLogs (при включении соответствующего чит-кода). А ограничение на количество символов в пути вроде как снять можно, во всяком случае, в Windows 10.

Вот, к примеру:
https://winitpro.ru/index.php/2016/06/10/kak-v-windows-10-otklyuchit-ogranichenie-na-dlinu-puti-v-260-simvolov/

**Comment by gjf** [comment]
Спасибо за наводку, про этот параметр не знал. Впрочем, в статье они немного промазали с уровне групповых политик, где он находится :)

Проблема в том, что не у всех десятка. Ну да что есть - то есть.
