### ISSUE TITLE
[Feature Request]  Possibility to hide and show tray icon via a terminal command and possibility to start the app minimized

### ISSUE THREAD

**Issue by emanuelep57** [kotatogram/kotatogram-desktop#160]
Hello everyone, I am a bspwm and polybar user, I'd like to enable and disable my tray bar via a script or terminal command, but I can't due to the fact that to disable the tray icon for kototogram I need each time to go into settings and disable the tray icon manually. Also a good idea would be the possibilty to start the app minimized or to disable notifcation as option when starting the application..basically I'd like the possibility of "customizing" or better modify the settings of the app via terminal

**Comment by ilya-fedin** [comment]
Why do you need this?
PS: https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by emanuelep57** [comment]
> Why do you need this?
> PS: https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by emanuelep57** [comment]
Well, the reason is purely aesthetic, I'd like the possibility of enabling and disabling the tray icon simply from terminal or via a Key binding without having to open the app and the settings each time

**Comment by ilya-fedin** [comment]
> Well, the reason is purely aesthetic

I don't want to spend a lot of time just for aesthetic :/

> I'd like the possibility of enabling and disabling the tray icon simply from terminal or via a Key binding without having to open the app and the settings each time

Why do you need to disable/reenable it so frequently?

**Comment by emanuelep57** [comment]
> I don't want to spend a lot of time just for aesthetic :/
Well this seems like a fair point, but disabling the tray icons is not really a lot of time 

> Why do you need to disable/re-enable it so frequently?
Well as I said it takes space to my Bspwm layout especially when I am in monocle layout but at the meantime I don't want to close kotatogram or have the trouble to go into settings and disabling it from there each time I don't need it

**Comment by ilya-fedin** [comment]
> Well this seems like a fair point, but disabling the tray icons is not really a lot of time

A lot of time is to add new command line switch. A switch to change settings would require adding new command to tdesktop's single instance socket, what is a lot of effort. The cmdline switches mechaism is not designed for using for end users, so it requires adding the switch in multiple places in the codebase (+ updaters on each system). And etc, etc.

> Well as I said it takes space to my Bspwm layout especially when I am in monocle layout but at the meantime I don't want to close kotatogram or have the trouble to go into settings and disabling it from there each time I don't need it

I don't really understand all what you wrote, but if you don't like it, why you re-enable it again and again?

**Comment by emanuelep57** [comment]
> > Well this seems like a fair point, but disabling the tray icons is not really a lot of time
> 
> A lot of time is to add new command line switch. A switch to change settings would require adding new command to tdesktop's single instance socket, what is a lot of effort. The cmdline switches mechaism is not designed for using by end users, so it requires adding the switch in multiple places in the codebase (+ updaters on each system). And etc, etc.
> 
> > Well as I said it takes space to my Bspwm layout especially when I am in monocle layout but at the meantime I don't want to close kotatogram or have the trouble to go into settings and disabling it from there each time I don't need it
> 
> I don't really understand all what you wrote, but if you don't like it, why you re-enable it again and again?

Well, let me explain it better...I find the tray icon useful, but when using windows in a fullscreen is slightly unpleasant to me (due to my desktop configuration) , I just thought that would have been an easier job to implement this as a terminal command, I can also understand that almost no user faces this specific need

**Comment by ilya-fedin** [comment]
You cant disable taskbar icon and have only tray icon

**Comment by emanuelep57** [comment]
> You can disable taskbar icon and have only tray icon
I guess it's alright, thank you for your time and your help!
