### ISSUE TITLE
Image is not bundling with caption in  unquoted

### ISSUE THREAD

**Issue by shamnad-sherief** [kotatogram/kotatogram-desktop#162]
I am trying to unquote forward a message with text captioned in an image. But the image is not forwading with the text. Only the text message is being forwaded.

**Comment by ilya-fedin** [comment]
6 months wasn't enough to make the feature stable :laughing:

**Comment by RadRussianRus** [comment]
@shamnad-sherief Can't reproduce bug though. What Kotatogram version? And which forwarding mode do you use?

Also it would be helpful to provide steps to reproduce as full as possible.

**Comment by ilya-fedin** [comment]
@RadRussianRus looks like the reporter went MIA, there's probably no reason to have the issue open
