### ISSUE TITLE
[Feature Request] перемещение к последнему сообщению по правому клику на круглую кнопку

### ISSUE THREAD

**Issue by f242** [kotatogram/kotatogram-desktop#167]
реквесчу перемещение к последнему сообщению чата по правому клику, актуально при чтении переписки в чате между кем-нибудь, левый клик перемещает тупо на шаг назад, а правый никак не задействован
![image](https://user-images.githubusercontent.com/10371194/115996608-a12cde00-a5e8-11eb-9a6b-574a34d57c2f.png)

**Comment by RadRussianRus** [comment]
Уже есть, правда, не по ПКМ, а под Ctrl+ЛКМ.

**Comment by f242** [comment]
ну просто это не очень хорошее решение, нужно 2 руки, клавиатура...

**Comment by RadRussianRus** [comment]
Посмотрим, может, в будущем приделаю. Но я так-то говорил к тому, что технически, функция есть.
