### ISSUE TITLE
[Feature Request] Hide messages from blocked users in group chats.

### ISSUE THREAD

**Issue by h0cheung** [kotatogram/kotatogram-desktop#17]
Telegram allows us to block users, but in group chats, blocked users' messages still annoys us. So there is some clients that can hide these messages, such as [telegreat](https://github.com/Sea-n/tdesktop). I think kotatogram should add this feature, too.

**Comment by NamedKitten** [comment]
Seconded.

**Comment by alsoGAMER** [comment]
Also nekogram has this feature on android

**Comment by trochdewei** [comment]
It's highly useful feature, we are waiting it in telegramdesktop since 2015

**Comment by ilya-fedin** [comment]
I'm working on this, hidding works perfectly, but I have problems with showing:
![photo_2020-06-14_21-51-10](https://user-images.githubusercontent.com/17829319/84600288-c6e54480-ae67-11ea-99a7-0f5b238f119b.jpg)
![photo_2020-06-14_21-51-12](https://user-images.githubusercontent.com/17829319/84600289-c8af0800-ae67-11ea-9b83-516817d0d1d0.jpg)
If anyone have ideas, would be great.
https://github.com/ilya-fedin/kotatogram-desktop/commit/a874a6be5b30fc85f48f49ce08a86776526efb74

**Comment by RadRussianRus** [comment]
Sadly, it seems that this feature violates Telegram API ToS.

Nekogram has removed it by request of Telegram, meaning that this feature is not allowed.
https://t.me/nekoupdates/52

**Comment by ilya-fedin** [comment]
I added that feature to my AUR packages by a patch

https://aur.archlinux.org/packages/kotatogram-desktop/
https://aur.archlinux.org/packages/kotatogram-desktop-dynamic-bin/
