### ISSUE TITLE
[Feature Request] Icon on task bar does not consistent with icon on tray

### ISSUE THREAD

**Issue by 29988122** [kotatogram/kotatogram-desktop#170]
### Is your feature request related to a problem?
When tray icon is changed
![圖片](https://user-images.githubusercontent.com/5474709/117282470-5ee08800-ae97-11eb-8998-ab22aca32caf.png)
![圖片](https://user-images.githubusercontent.com/5474709/117282482-630ca580-ae97-11eb-801d-52ad105e8933.png)

The task icon does not change. This cause inconsistensies.
![圖片](https://user-images.githubusercontent.com/5474709/117283041-fc3bbc00-ae97-11eb-825d-a6b94b863310.png)

Windows version of Kotatogram.

### Describe the solution you'd like
Make them the same.

### Describe alternatives you've considered
If we can customize icon on both task and tray (say I still prefer telegram's official icon), it'd be ideal.
I love your fork, it's useful and not too far from the original fork with TONS of friendly features 

![圖片](https://user-images.githubusercontent.com/5474709/117282962-e4643800-ae97-11eb-91cc-c69058dc591d.png)
Very proud.

But still, I'd like an option for me to customize, if there's a possiblilty. 

Thank you, @RadRussianRus.

**Comment by ilya-fedin** [comment]
That icon is also set as window icon:
https://github.com/kotatogram/kotatogram-desktop/blob/745bb0a4e06b7eede6d2a39301e6cb4655303ac3/Telegram/SourceFiles/window/main_window.cpp#L124-L138

**Comment by ilya-fedin** [comment]
@RadRussianRus can you close the issue since the reporter ignored my post?

**Comment by 29988122** [comment]
It's not like that I ignored your comment, just they are *four* different things.

1. tray icon 
![圖片](https://user-images.githubusercontent.com/5474709/120059911-f72cef80-c086-11eb-8915-82eb4dced4e2.png)

2. task bar icon
![圖片](https://user-images.githubusercontent.com/5474709/120059912-fa27e000-c086-11eb-92ac-a858d32ff04e.png)
3. window icon
![圖片](https://user-images.githubusercontent.com/5474709/120059919-090e9280-c087-11eb-9742-433d4e0a5bd5.png)

And the issue is "inconsistent", not "I want to file feature request as I wish".

**Comment by ilya-fedin** [comment]
@29988122 i said that this is already implemented. That icon is set to all the places.

**Comment by ilya-fedin** [comment]
I don't see a reason to have that issue open. Kotatogram already sets custom icon in all places in the code. If you have some other icon somewhere, that means Windows overrides it and Kotatogram can't do anything about that.
