### ISSUE TITLE
[Feature Request] Upload files in alphabetical/numerical order

### ISSUE THREAD

**Issue by tissole** [kotatogram/kotatogram-desktop#172]
### Is your feature request related to a problem?
Now files get uploaded in random order.

### Describe the solution you'd like
I will like to upload them in alphabetical/numerical order.

**Comment by tissole** [comment]
An update. Files are uploaded correctly only when added using the upload button, but lose their order when uploaded by drag and drop.

**Comment by tissole** [comment]
The problem still persists. I tested with 200 text files and only the first 50 were uploaded in order when using the upload button.

**Comment by RememberTheAir** [comment]
Yes, there was no update in the past 3 days

**Comment by tissole** [comment]
This issue is solved now. Using button, files are uploaded in order, only drag and drop uploads files random.
