### ISSUE TITLE
Voice record crash

### ISSUE THREAD

**Issue by juxuanu** [kotatogram/kotatogram-desktop#174]
### Steps to reproduce
1. Open a chat
2. Click on record voice message
3. Record more than ~0.5s of message

### Expected behaviour
It should record from the input audio device.

### Actual behaviour
Core dumps.

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** k1.4.12.g40df43998

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: https://aur.chaotic.cx/ 's package.

**Used theme**: Default (?)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
-- I insert the video --

https://user-images.githubusercontent.com/24759034/117579632-196cc680-b0f4-11eb-85d0-a1f0b66b65ad.mp4

</details>

**Comment by ilya-fedin** [comment]
It's bugged ffmpeg 4.4 in arch repos

**Comment by juxuanu** [comment]
How do you know? I see no bug report in Arch's bugtracker.

**Comment by ilya-fedin** [comment]
Almost everyday Arch users open issues (and they being closed since it's not reproducible on official builds) about that in tdesktop repo.

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
