### ISSUE TITLE
[Feature Request] Change emoji/sticker menu popup from mouse over to click

### ISSUE THREAD

**Issue by iamtherobin** [kotatogram/kotatogram-desktop#181]
### Is your feature request related to a problem?
Not a problem but an annoyance.

### Describe the solution you'd like
Right now the emoji/stick menu will pop up when the mouse is over the emoji bottom in a chat. This is really annoying as whenever my cursor happens to pass over the button incidentally, it popups.

### Describe alternatives you've considered
An option to change this button to click only instead of mouse over.

### Additional context
<a href="https://imgur.com/VgQrZsR"><img src="https://i.imgur.com/VgQrZsRm.png" title="source: imgur.com" /></a>

**Comment by ilya-fedin** [comment]
That's already implemented

**Comment by iamtherobin** [comment]
Wow I must be blind. I went through the settings and didn't see it until you mentioned it.
