### ISSUE TITLE
[Feature Request] файлы

### ISSUE THREAD

**Issue by yo8z6gv** [kotatogram/kotatogram-desktop#186]
при пересылке файлов всегда неверный порядок отправленных файлов. порядок всегда точен если пересылать из избранного версии 2.2.0 и ниже официального телеграма, на поздних не тестировал
при пересылке в избранное и попытку там все правильно отсортировать чтобы оттуда уже в нужный чат отправить, вечно склеивает сообщения без возможность разъединения
при загрузке байтовых файлов — порядок отправленных файлов не соответствует изначальному списку
нет кнопки обновления чата чтобы увидеть сообщения как есть. в настоящее время реализуется поиском по дате очень давних сообщений, таким образом переходя к ним загружается история тех дат выгружая историю сообщений где был, возвращаясь обратно через стрелочку вниз или также по поиску — список будет обновлен.
файлы без комментария сокращают свои названия в середине на "..." из-за чего не видно полного названия. вынужден постоянно нажимать "сохранить как" из выпадающего списка только чтобы посмотреть имя файла; или через поиск сообщений искать и там смотреть на время отправки, а само окно с контактами растянуть максимально вправо.
файлы отправленные с статусом "ошибка" никак нигде не маркируются, кроме как на самой позиции. в итоге могут быть пропущены некоторые файлы если отправлять свыше 2000 файлов единоразово, в основном потому что очень большой прогруженный чат может крашнуть программу. так например только официальная версия телеграма 2.2.0 и ниже могут отправлять от 10000 файлов разово одним сообщением без вылетов.

в экспорте истории чата нет выбора в "файлы" конкретных пользовательских расширений форматов.
при экспорте json без файлов, в списке будет написано что файла нет; иначе говоря чтобы в сторонней программе посмотреть все сообщения как есть, нужно использоваться исключительно html, там названия файлов отображаются

к сожалению так и не смог решить проблему с группированием сообщений. при перепрыгивании с 2.2.0 на современные версии, постоянно где-то будут сгрупированные сообщения, а разделить их и сохранить последовательность 133 сообщений ни через это приложение, ни через telegraph не получается, даже используя избранное. при пересылке 100 файлов 1900мб веса обязательно порядок будет нарушен, а при пересылке с другой версии в конечном канале неверный порядок.
самая большая проблема группированных файлов, что они не индексируются и в поиске будет "альбом"; а также из альбома нельзя выдернуть один файл ни в десктопной версии телеграм, ни в kotatogram

**Comment by ilya-fedin** [comment]
Пипец, так сумбурно написано, я нифига не разобрал. Такое ощущение, что несколько несвязанных вещей запихано в один пост (чего делать нельзя).

**Comment by RadRussianRus** [comment]
Так и есть, судя по всему. Я обычно пытаюсь разобрать, но тут уж слишком сложно для восприятия. Эту я закрываю, лучше создайте по каждой отдельно.

И да, версии 2.2.0 сто лет в обед, тестируйте на более новых, пожалуйста (актуальный стабильный TDesktop на момент сообщения: 2.8.4).

Плюс, если ваша проблема связана конкретно с Telegram Desktop, попробуйте там создавать issue (только на английском, и не такую же огромную, как здесь).
