### ISSUE TITLE
[Question] Code via SMS in TD and KD

### ISSUE THREAD

**Issue by adevoss** [kotatogram/kotatogram-desktop#196]
Having a phone with only call/SMS I had to switch to KD.

Can someone explain why I can use KD and not TD? What change has Telegram made?
Who is sending the SMS message?
Does KD keep SMS support in the future?

**Comment by ilya-fedin** [comment]
Who knows, it's all done on their server side that is proprietary. Most likely they blacklisted tdesktop's API_ID and API_HASH.

**Comment by adevoss** [comment]
Got it. Thanks.
Only mobile app would force out dumb phones. That's bad IMO.
Time will tell.
