### ISSUE TITLE
Kotatogram keeps crashing when trying to open any file dialog

### ISSUE THREAD

**Issue by TruncatedDinosour** [kotatogram/kotatogram-desktop#213]
### Steps to reproduce
1. open kotatogram
2. open a file dialog (I.e try to upload a file)
3. crash

### Expected behaviour
Should open a file dialog

### Actual behaviour
It crashes the client

### Configuration
**Operating system:**
Arch Linux, X11

**Version of Telegram Desktop:**
```
Name            : kotatogram-desktop-bin
Version         : 1.4.2-1
Description     : Experimental Telegram Desktop fork with option to select custom fonts. - Static binaries
Architecture    : x86_64
URL             : https://github.com/kotatogram/kotatogram-desktop
Licenses        : GPL3
Groups          : None
Provides        : kotatogram-desktop
Depends On      : fuse
Optional Deps   : xdg-desktop-portal: for native file dialogs, do not forget to install one of backends
                  xdg-utils: for automatic opening of URLs, files and directories in proper applications [installed]
Required By     : None
Optional For    : None
Conflicts With  : kotatogram-desktop  kotatogram-desktop-dynamic-bin
Replaces        : None
Installed Size  : 77.32 MiB
Packager        : Unknown Packager
Build Date      : Sun 22 Aug 2021 04:38:59 EEST
Install Date    : Sun 22 Aug 2021 04:39:24 EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: [the AUR](https://aur.archlinux.org/packages/kotatogram-desktop-bin/)

**Used theme**: [telegram-gruvbox-theme](https://github.com/gilbertw1/telegram-gruvbox-theme)

<details><summary><b>Logs</b>:</summary>
(kotatogram-desktop:1120193): GdkPixbuf-WARNING **: 04:42:49.671: Cannot open pixbuf loader module file '/usr/lib/x86
64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open

(kotatogram-desktop:1120193): Gtk-WARNING **: 04:42:54.059: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
</details>

**Comment by ilya-fedin** [comment]
looks like something is wrong with gtk on your system

**Comment by TruncatedDinosour** [comment]
Oh

**Comment by TruncatedDinosour** [comment]
This fixed it:
```sh
su

mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0

gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
 ```
 
 sorry that I missed it :)

**Comment by ilya-fedin** [comment]
oh, looks like it's because appimage has bundled gdk-pixbuf... it's a pity linuxdeployqt doesn't remove dependencies of libraries from exclude-list
