### ISSUE TITLE
[Feature Request] Поиск по картинке в Yandex и Google

### ISSUE THREAD

**Issue by Neurotoxin001** [kotatogram/kotatogram-desktop#219]
Бывает нужно проверить картинку на баянность, а скачивать её и заливать на гугл\яндекс вручную — долго.

Хотелось бы делать это в 1 клик из контекстного меню. После клика пикча скачивается в папку загрузок из заливается сюда:
https://www.google.com/searchbyimage?image_url=https://avatars.githubusercontent.com/u/54968358
https://yandex.com/images/search?rpt=imageview&url=https://avatars.githubusercontent.com/u/54968358

Может быть есть апи для вставки и локальных изображений.

**Comment by antshar** [comment]
Плюсую. Тоже порой приходится проводить поиск по картинке.
На данный момент, вместо скачивания, копирую картинку, а использование сочетания Ctrl+V на странице яндекс картинок автоматически подхватывает ее из буфера и ищет по ней. К сожалению, гугл так не умеет.

На счет апи для десктопа не уверен, но в веб версии поиск по картинке в гугл из контекстного меню работает.
