### ISSUE TITLE
Freeze after close kotatogram v1.4.1

### ISSUE THREAD

**Issue by azkadev** [kotatogram/kotatogram-desktop#224]
### Steps to reproduce

Every time I exit the kotatogram application, my laptop can only move the mouse, all the keyboard buttons don't work, is this a bug?
my /pc potato :(

my laptop specs

```bash
System:
    OS: Linux 5.13 Pop!_OS 21.04
    CPU: (2) x64 Intel(R) Celeron(R) CPU 887 @ 1.50GHz
    Memory: 4.73GB / 7.57GB
    Containers: Yes
    Shell: 5.1.4 - /bin/bash
```

### Expected behaviour

please fix the freeze screen after the application exite
![Screenshot from 2021-09-20 19-35-25](https://user-images.githubusercontent.com/82513502/134003162-31db935d-c624-42e9-93fd-32f049b17860.png)
d

### Actual behaviour

I tried to exit the application, but after that only the cursor could move, others couldn't, and only the power button could be pressed, even then I had to press long to turn it off,

This freeze screen has happened repeatedly only when closing the kotatogram application, there are no other applications that I run but the result is the same freeze can't be moved

### Operating system

pop os 21 ubuntu debian based

### Version of Kotatogram Desktop

1.4.1

### Installation source

Static binary from official website

### Logs

```shell
i dont know how to get logs
```

**Comment by ilya-fedin** [comment]
Never happened to me. Honestly saying, I have no idea how to debug that.
