### ISSUE TITLE
No or Very Delayed notifications

### ISSUE THREAD

**Issue by LakesideMiners** [kotatogram/kotatogram-desktop#226]
### Steps to reproduce

1. Get a Message

### Expected behaviour

You should get a notification right away

### Actual behaviour

You don't get a notification, or, its very Delayed.
This dost seem to happen with the snap or flatpak versions. but, I want to have auto updates.
I can deal without the auto updates, but I wanted to make this issue known as well.

### Operating system

Linux Mint 20.2 Cinnamon

### Version of Kotatogram Desktop

1.4.4 Beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Just updated Kotatogram to check the issue and I can say I can't reproduce it

**Comment by LakesideMiners** [comment]
its not occuring anymore for me, closing
