### ISSUE TITLE
[Question] не работает авторизация в одном акке

### ISSUE THREAD

**Issue by yo8z6gv** [kotatogram/kotatogram-desktop#246]
раньше открывалась программа вместе с моим акком, теперь же при запуске сразу вылеает с этой ошибкой:
[log.txt](https://github.com/kotatogram/kotatogram-desktop/files/7449140/log.txt)

удаление tdata и всех файлов кроме Kotatogram.exe не помогло
не помогло даже отключение всех сессий на самом акке..
вообще хз в чем проблема.
во всех остальных акках клиент работает :(

**Comment by ilya-fedin** [comment]
Это переполнение int'а из-за автоудаления через месяц :(

**Comment by RadRussianRus** [comment]
Тут поможет только выйти из чата, где есть автоудаление через месяц (к примеру, через официальный клиент) или поставить бету, в ней проблема решена.
