### ISSUE TITLE
Crash on start, bus error and error loading libjpeg.so (AppImage)

### ISSUE THREAD

**Issue by nick87720z** [kotatogram/kotatogram-desktop#249]
### Steps to reproduce

1. Unpack Kotatogram appimage, making its dir readonly (e.g. to /opt/Kotatogram).
2. Enter that dir, start Kotatograb - permission denied.
3. `cd ~ && /opt/Kotatogram/Kotatogram` results to this:
```
error: : cannot open
error: : cannot open
error: : cannot open
Bus error
```
(last line printed on russion even with LANG=en, so I edited this text just to make it clear)
4. Run with gdb, as described in issue #223: doesn't run, giving error loading shared library libjpeg.so, which I have installed for both 32 and 64bit as libjpeg-turbo (exact dirs - /usr/lib and /usr/lib64)

### Expected behaviour

First run was successful right at line 1 - from /opt/Kotatogram workdir, which I installed as root, while running Kotatogram as regular. So should run without problem even if current dir is readonly.

### Actual behaviour

Crashes with some "bus error" on regular run (dbus is ok) and from libjpeg loading error if attempted from gdb.

### Operating system

gentoo-based (calculate)

### Version of Kotatogram Desktop

1.4.1

### Installation source

Static binary from official website

### Logs

It crashed, as I suspect from log, due to some QXcbConnection error. Unfortunally I closed terminal with that log, but that's different issue (not so serious as actual one).
It crashed on attempt to open link, invoking gtk app, which I suspect to be reason, although it did not crash app itself.
Actual results are in steps, per each step.

(I edited head, removing code style from text in Logs)

**Comment by ilya-fedin** [comment]
> (last line printed on russion even with LANG=en, so I edited this text just to make it clear)

Are you sure that's the right translation? This text is printed by your shell most likely, so you should launch a nested shell instance with LANG=C

**Comment by nick87720z** [comment]
My original LANG is ru. I tried once claws-mail runing with LANG=C, which caused non-ascii chars to not work in text fields, so now I use LANG=en for unlocalized logs. However, I made switch to russion on start of first (and last) run.

**Comment by ilya-fedin** [comment]
Will you do what I asked?

**Comment by nick87720z** [comment]
I assume it's necessary to hunt this bug.

**Comment by ilya-fedin** [comment]
So, will you?

**Comment by nick87720z** [comment]
Ah. You asked to run with LANG=C. This time it prints it unlocalized:
```
./Kotatogram 

(Kotatogram:20746): Kotatogram-WARNING **: 19:48:14.753: GTK integration is disabled, some features unavailable.
error: : cannot open
error: : cannot open
error: : cannot open
Bus error
```

**Comment by ilya-fedin** [comment]
I asked to run your shell with either LANG=C or LANG=en, so the line would be in original english text, I assume you translated the line wrongly since I never seen anything like that

**Comment by nick87720z** [comment]
yes, I ran Kotatogram from `LANG=C bash`

**Comment by ilya-fedin** [comment]
What `echo $?` would print after that error?

**Comment by nick87720z** [comment]
it seems returned 135

**Comment by nick87720z** [comment]
Found something related here:
https://github.com/Codeception/robo-paracept/issues/28

There are cases when it returns 128 + <signal from OS>, with signal 7 being SIGBUS

**Comment by nick87720z** [comment]
Bus error disappeared after system reboot.
Oh, btw. While bug was active, unpacking the appimage did not complete even in home dir, that could be reason for error loading libjpeg.so.

**Comment by ilya-fedin** [comment]
So the issue can be closed?

**Comment by nick87720z** [comment]
Yes, I guess it's rather invalid. Appimage corner case.
