### ISSUE TITLE
[Feature Request] Фильтрация сообщений в каналах\группах со скрытием

### ISSUE THREAD

**Issue by WerctFourth** [kotatogram/kotatogram-desktop#253]
### Is your feature request related to a problem?

Нет

### Describe the solution you'd like

Добавить фильтр сообщений, к примеру, по внешним ссылкам, или по ключевым словам (или по регексу, тоже можно), при совпадении сообщение в группе\канале скрывается в полоску, подобную той, как сейчас "Unread Messages" отображается, можно раскрыть по требованию. Желательно включение\отключение отдельно для каждого канала\группы.
Странно, что до сих пор нигде такого не встретил, только упоминание фичреквеста пару раз на реддите без особых положительных результатов.

### Describe alternatives you've considered

Нет

**Comment by ilya-fedin** [comment]
Известно, что за фильтрацию сообщений прилетают письма счастья от команды Telegram за нарушение API ToS. Видимо, они считают, что только сервер имеет право фильтровать.

**Comment by WerctFourth** [comment]
> Известно, что за фильтрацию сообщений прилетают письма счастья от команды Telegram за нарушение API ToS. Видимо, они считают, что только сервер имеет право фильтровать.

Т.е. прибегают и нагибают за полностью клиентскую фичу? М-да, спасибо за ответ, надо переходить на сигнал для личных переписок 😐

**Comment by ilya-fedin** [comment]
Да, прибегают и грозятся кидать абузы в сторы и банит API-ключ, есть прецедент с Nekogram: https://t.me/nekoupdates/52 (последний пункт)
