### ISSUE TITLE
Unexpected behavior - slow scroll speed

### ISSUE THREAD

**Issue by bnn1** [kotatogram/kotatogram-desktop#254]
### Steps to reproduce

1. Open app
2. Scroll any chat/chats list
3. Be annoyed how slow it is

### Expected behaviour

App scrolling is as fast as native Telegram Desktop's (or Kotatogram 1.4.1)

### Actual behaviour

Scrolling inside app is annoyingly slow

### Operating system

ArcoLinux, KDE

### Version of Kotatogram Desktop

1.4.4 Beta (TD 3.1)

### Installation source

Other (unofficial) source

### Logs

```shell
Scrolling speed in kotatogram-desktop-dynamic-bin aur package is OK. Couldn't build kotatogram-desktop due to some errors in making the package.
```

**Comment by ilya-fedin** [comment]
I can't reproduce, scrolls just fine

**Comment by bnn1** [comment]
Experiencing same problem with [kotatogram-desktop-bin](https://aur.archlinux.org/packages/kotatogram-desktop-bin/)(v1.4.5) package.

**Comment by bnn1** [comment]
The bug no more reproducable on newest version of Kotatogram.
