### ISSUE TITLE
[Question] Telegram says out dated app will stop working soon.

### ISSUE THREAD

**Issue by 3k2** [kotatogram/kotatogram-desktop#256]
![image](https://user-images.githubusercontent.com/11908261/144428137-3645479f-7346-48fc-929e-8f6a3cf3d16d.png)

do we need to update or ?

**Comment by aikins01** [comment]
same problem here

**Comment by SoHardDay** [comment]
![изображение](https://user-images.githubusercontent.com/46621615/144606199-104d1761-5e00-4436-a096-b771c1d8478c.png)

**Comment by RadRussianRus** [comment]
Same as #257.
