### ISSUE TITLE
Messages aren't updating

### ISSUE THREAD

**Issue by 3k2** [kotatogram/kotatogram-desktop#257]
### Steps to reproduce

today for some reason I stopped getting messages at kotatogram. I noticed this because I was looking at active channels and official telegram and kotatogram didn't have same amount of messages also direct messages to me didn't update in kotatogram as well. This would be related to my previous post [Please update your app to the latest version. The version you are using is out of date and will stop working soon.](https://github.com/kotatogram/kotatogram-desktop/issues/256)

### Expected behaviour

To receive messages

### Actual behaviour

won't receive messages/updates

### Operating system

Windows 11

### Version of Kotatogram Desktop

Version 1.4.1

### Installation source

Static binary from official website

**Comment by RadRussianRus** [comment]
You can update to 1.4.4 beta, it should work fine. I'm hoping to release the stable version on same TD sources as beta in the coming days.
