### ISSUE TITLE
 [Feature Request] Copy ID in right click context menu strip

### ISSUE THREAD

**Issue by graysuit** [kotatogram/kotatogram-desktop#274]
### Is your feature request related to a problem?

Many times we have to use third party bots to get IDs of channel/group/user for various purpose. But many times, some users don't have usernames and we left with preparing our own script. Its really time consuming and painful.

### Describe the solution you'd like

Right clicking on any channel/group/user can allow us to show context menu strip that also includes "Copy ID". and it copies ID into clipboard.

### Describe alternatives you've considered

If you can guide me which lines should I change, then I can easily fork and invent that feature.

### Additional context

This feature is very important. Specially for developers. In discord, this feature is available. Just we need to enable developer mode. Please see screenshot.
![Untitled](https://user-images.githubusercontent.com/54432616/144650412-e95a3b2d-d5c5-41d2-a532-8e6014d47159.png)

**Comment by graysuit** [comment]
also a duplicate of: https://github.com/telegramdesktop/tdesktop/issues/17335

**Comment by ilya-fedin** [comment]
Why can't you just select and copy ID from user profile?

**Comment by graysuit** [comment]
@ilya-fedin There's no such option or feature. See:
![Untitled](https://user-images.githubusercontent.com/54432616/146672437-d4b302ef-6c02-4913-8857-9f6a8617616b.png)

**Comment by ilya-fedin** [comment]
In user profile, not in context menu

**Comment by graysuit** [comment]
@ilya-fedin Where ?
![Untitled](https://user-images.githubusercontent.com/54432616/146672507-f3db850c-6481-4440-875c-18032de7a8b9.png)

**Comment by ilya-fedin** [comment]
Have you enabled that feature in Kotatogram settings?

**Comment by graysuit** [comment]
Is this present in Kotatogram and not in tdesktop ?

**Comment by ilya-fedin** [comment]
yeah

**Comment by graysuit** [comment]
ok, then I download and check it

**Comment by ilya-fedin** [comment]
it's funny to request a feature before checking whether it's present or not

**Comment by graysuit** [comment]
As mentioned in README, its fork of tdesktop. So I thought it may NOT have it.
Anyway its fun for me as well. lol

**Comment by ilya-fedin** [comment]
A fork, just like non-forks, may have and may not have any feature, you can't know before checking

**Comment by graysuit** [comment]
Yeah, I'm kind of lazy user human. 
I checked, and it has it. Thanks so much @ilya-fedin for help to open my eyes.
![Untitled](https://user-images.githubusercontent.com/54432616/146672765-796bdac7-ad12-43d3-b3a7-e5630425f32f.png)

**Comment by graysuit** [comment]
Also Thanks kotatogram Team for making such feature available.
