### ISSUE TITLE
Unfocused auto-scroll doesn't auto-scroll on Wayland

### ISSUE THREAD

**Issue by the-blank-x** [kotatogram/kotatogram-desktop#280]
### Steps to reproduce

1. Go to Kotatogram Settings and enable Unfocused auto-scroll
2. Open a chat and unfocus window
3. Have messages in the chat until they become unread

### Expected behaviour

Unfocused auto-scroll should scroll the chat while the window is unfocused

### Actual behaviour

It doesn't

### Operating system

Arch Linux, swaywm

### Version of Kotatogram Desktop

1.4.6

### Installation source

Other (unofficial) source

### Additional Info
It only doesn't auto-scroll on Wayland since [Kotatogram can't determine if the window is overlapped or not](https://github.com/kotatogram/lib_ui/blob/d9274f06bddccf0e5f4deabe641bafdd3b453c3f/ui/platform/linux/ui_utility_linux.cpp#L478)

**Comment by ilya-fedin** [comment]
Yeah, there's no enough API to implement that on Wayland

**Comment by the-blank-x** [comment]
Should `IsOverlapped` or `doWeMarkAsRead` be patched to return true

**Comment by ilya-fedin** [comment]
The option should be hidden, I think

**Comment by ilya-fedin** [comment]
Should be fixed by #285
