### ISSUE TITLE
Messages with the new "spoiler" option don't show

### ISSUE THREAD

**Issue by ccrowles** [kotatogram/kotatogram-desktop#289]
### Steps to reproduce

Try to read a message that it's written with the new "spoiler" formatting.

### Expected behaviour

You should be able to read the message.

### Actual behaviour

The whole message is replaced with this:

![image](https://user-images.githubusercontent.com/12866474/148658143-b004d830-9f9a-476e-8cff-6839302c50f8.png)

### Operating system

Windows 10 Pro version 20H2

### Version of Kotatogram Desktop

1.4.8 x64 (TD 3.3)

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
The answer is in TDesktop version Kotatogram based on. :)

Spoilers were added in TD 3.3.2 beta. They will be added once sources are updated.
