### ISSUE TITLE
Protected content messages support

### ISSUE THREAD

**Issue by Olegt0rr** [kotatogram/kotatogram-desktop#290]
### Steps to reproduce

1. Try to receive protected message from bot

### Expected behaviour

Message received successfully.

### Actual behaviour

<img width="492" alt="Screenshot 2022-01-14 at 17 02 18" src="https://user-images.githubusercontent.com/25399456/149527586-44343ab9-ed68-488e-a272-41370792eb94.png">

### Operating system

macOS

### Version of Kotatogram Desktop

1.4.8

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
The tdesktop version kotatogram is based on didn't support this kind of messages yet

**Comment by Olegt0rr** [comment]
@RememberTheAir, this is the reason to rebase :)

**Comment by EricKotato** [comment]
See https://github.com/kotatogram/kotatogram-desktop/issues/289#issuecomment-1008133314.
