### ISSUE TITLE
Send code via SMS is no more working

### ISSUE THREAD

**Issue by ociebieda** [kotatogram/kotatogram-desktop#292]
### Steps to reproduce

Start Messaging - Or log in using your phone number - Send code via SMS

### Expected behaviour

Code sent in sms

### Actual behaviour

Message "Please enter the code that was sent to you via Telegram or log in via QR code"

### Operating system

Windows 10

### Version of Kotatogram Desktop

1.4.8

### Installation source

Static binary from official website

### Logs

```shell
[2022.01.19 22:26:47] RPC Error: request 12 got fail with code 406, error SEND_CODE_UNAVAILABLE
```

**Comment by EricKotato** [comment]
If server replied that it can't send authorization code via SMS, there is nothing I can do with it.
