### ISSUE TITLE
Clicking on a native notification does not open the correct chat/channel

### ISSUE THREAD

**Issue by pioneer** [kotatogram/kotatogram-desktop#3]
### Steps to reproduce
1. Run Kotatogram
2. Select "Settings -> Notifications -> Use system native notifications" option
3. Wait for a notification to appear, and click on it

### Expected behaviour
A chat or channel the notification appeared belongs to should be opened by clicking on the notification.

### Actual behaviour
If Kotatogram window is opened, it turns foreground, but with no proper chat/channel selection. If Kotatogram is in tray only, nothing happens.
**This is also weird:** I'm using two Kotatogram instances for my two Telegram accounts, with [this approach](https://gist.github.com/Nachtalb/ec590dc974f6ba4674972d4937b230be). In this case, having the following conditions met:
- two Kotatograms are running
- the Kotatograms have their windows opened, either in the background or foreground (not only in the system tray)
clicking on a native notification brings to the foreground the last executed Kotatogram instance. Usually, it's the one for the second of two my accounts, despite on which notification I have clicked - from the first or the second account. If two Kotatograms are in the tray, nothing happens. If there's only one Kotatogram opened, and the other is in the tray, the opened window turns foreground by clicking on a native notification.

**No such bug is happening when using the Telegram's own notifications, it's all perfect in this case.**
**No such bug is happening with the official Telegram or Bettergram.**

### Configuration
**Operating system:** Manjaro Cinnamon (latest)

**Version of Kotatogram Desktop:** 1.1.2

**Comment by ilya-fedin** [comment]
How did you install Kotatogram?

**Comment by pioneer** [comment]
Good question, I have installed it using this AUR package https://aur.archlinux.org/packages/kotatogram-desktop, but never tried another one from here https://aur.archlinux.org/packages/kotatogram-desktop-bin. I have just tried it, and it seems the `kotatogram-desktop-bin` package works perfectly without the bugs described above. The only minor issue is that the `kotatogram-desktop` is using the system font by default, but the `kotatogram-desktop-bin` is using some predefined font by default. Anyway, I have set my preferred font in the settings right after installing and now I'm happy.

**Comment by ilya-fedin** [comment]
Yep, kotatogram-desktop package with my patches and I'll be very grateful if you help to debug this

**Comment by ilya-fedin** [comment]
I tested on MATE with the following configurations:
1. Two instances of Kotatogram with different workdirs but the same account - notifications are received only by one instance and looks like it's not your issue
2. Two instances of Kotatogram with different workdirs and accounts - notifications are received by both instances and the action invokes on both instances correctly
So I can't reproduce your bug, can you record dbus messages with Bustle?

**Comment by pioneer** [comment]
My case is the second case.

I have just tried to reinstall Kotatogram again using the first AUR package listed above from here https://aur.archlinux.org/packages/kotatogram-desktop. The bug does not happen using the second AUR package from here https://aur.archlinux.org/packages/kotatogram-desktop-bin, the difference between the two is that the first package (which has the bug) is built from source, and the second (which has no bug) is using precompiled binaries. So please check the PKBUILD script for the first package and the way it's built from source. Don't forget I'm using Manjaro with Cinnamon, so not sure if the bug exists, say, on Ubuntu or Linux Mint.

Now some more detailed observations for the Kotatogram built from source comparing to the one from binaries:

- yes, it has the bug described above
- but, I have found that the app works properly when clicking on a small arrow button at the bottom of a notification, in this case, the proper Kotatogram window is opened (either account 1 or 2), and the proper chat/channel is opened inside the window -- so no bug, great!
- by clicking on a notification outside the small arrow button, the bug still exists
- no such arrow button with Kotatogram from precompiled binaries, only source-built app has the button
- small detail (maybe another bug): the precompiled app has proper purple Kotatogram tray icons, but built-from-source app has blue original Telegram tray icons
- another small detail (and maybe another bug): the tray menu that appears when right-clicking on the tray icon of the precompiled app has an ugly font, but the same tray menu for the built-from-source app has the proper system font

The `bustle-git` package in AUR seems outdated and building it returns an error, so once I'll find a way to install it, Ill attach logs or whatever Bustle produces.

**Comment by ilya-fedin** [comment]
>     * by clicking on a notification outside the small arrow button, the bug still exists

This explains a lot. The old notification implementation added the `default` action, which emitted by clicking on a notification. But the new implementation uses the `action-icons` capability and doesn't set the `default` action. So by clicking on a notification, the window is focused by cinnamon itself and not tele(kotato)gram. And bug in the cinnamon notification daemon.



> So please check the PKBUILD script for the first package and the way it's built from source.

This patch was upstreamed, so...

**Comment by ilya-fedin** [comment]
I just pushed a possible fix to AUR, you can try it

**Comment by pioneer** [comment]
Just got and installed the update. Weird, I'm having this
```$ kotatogram-desktop
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)```

**Comment by ilya-fedin** [comment]
Okay, fixed
Precompiled package: https://github.com/ilya-fedin/kotatogramAUR/releases/tag/k1.1.2-4

**Comment by pioneer** [comment]
Just have installed and tested both `kotatogram-desktop` and `kotatogram-desktop-dynamic-bin`. Observations and thoughts:

- the `qt.qpa.plugin...` error is gone, I can install the package smoothly
- clicking on the arrow in a notification works perfectly as before
- clicking on a notification outside the arrow now works well in ~95% cases (not sure when those 5% are happening), sometimes it just brings a wrong Kotatogram window to the foreground w/o switching to the proper channel/chat -- need to play a bit with the windows in foreground, background, minimized etc.
- sometimes notifications are not shown in the Cinnamon notification applet after disappearing from the screen -- this is the applet where I can find all old notifications that have ever been shown on my desktop -- this bug happens rarely, and it's not about a particular notification, but rather this happens for all Kotatogram notifications until I restart Kotatogram (and the bug is gone after restart)
- notifications are too large for my liking, keeping in mind that arrow button, so I have finally switched to the maybe outdated `kotatogram-desktop-bin` static binaries version, which has narrower notifications, no arrow button and clicking on a notification works perfectly in this version

Let me know if I can debug the above somehow.

**Comment by ilya-fedin** [comment]
>     * sometimes notifications are not shown in the Cinnamon notification applet after disappearing from the screen -- this is the applet where I can find all old notifications that have ever been shown on my desktop -- this bug happens rarely, and it's not about a particular notification, but rather this happens for all Kotatogram notifications until I restart Kotatogram (and the bug is gone after restart)

Was this problem when a click outside the button did work wrong?

**Comment by pioneer** [comment]
No idea, I hadn't done any check against this Cinnamon notification bug before the latest Kotatogram build. Well, in fact, I only got an idea to test something like that with the latest build and so, therefore, discovered it in the latest build. Will continue testing, the bug is sporadic (currently not observing it anymore). If there's any such bug appears, I'll try to post it along with observed conditions.

There's still this bug happening, just please keep in mind - "the precompiled app has proper purple Kotatogram tray icons, but built-from-source app has blue original Telegram tray icons".

**Comment by ilya-fedin** [comment]
>     * small detail (maybe another bug): the precompiled app has proper purple Kotatogram tray icons, but built-from-source app has blue original Telegram tray icons

Try to clean the icon cache (~/.local/share/KotatogramDesktop/tdata/ticons)

>     * another small detail (and maybe another bug): the tray menu that appears when right-clicking on the tray icon of the precompiled app has an ugly font, but the same tray menu for the built-from-source app has the proper system font

Say thank you to Cinnamon devs for creating NIH XAppStatusIcon instead of implementing well-used StatusNotifierItem API. As a result Qt fallbacks to the old XEmbed API in which tray menu rendered by the app (static binary can't work with system fonts and themes)

**Comment by ilya-fedin** [comment]
>     * clicking on a notification outside the arrow now works well in ~95% cases

There was an error in cmake build rules: Q_OS_LINUX* macros were not defined and MainWindow::reactivateWindow did nothing.
Now it should work fine.

**Comment by pioneer** [comment]
Anyway, it's been a couple of days I'm using the Kotatogram built from source, just updated to have the latest build. Not seeing the clicking outside the arrow bug, for now, will let you know if there is any.

No tray menu ugly font in this version, so it seems to work well with XAppStatusIcon.

Cleaning the icon cache didn't help, it's got recreated with the same blue icons in tray. I'm seeing a lot of .png files in the icon cache folder, all of them are a 22x22 blue icon. I'm also seeing those files are somehow related to my current icon theme (Paper):

```
$ cd .local/share/KotatogramDesktop/tdata/ticons/
$ ls
iconmute_Paper_22_0.png     icon_Paper_22_1010.png  icon_Paper_22_1022.png  icon_Paper_22_1034.png  icon_Paper_22_1046.png  icon_Paper_22_1058.png  icon_Paper_22_1070.png  icon_Paper_22_1082.png  icon_Paper_22_1094.png
iconmute_Paper_22_1040.png  icon_Paper_22_1011.png  icon_Paper_22_1023.png  icon_Paper_22_1035.png  icon_Paper_22_1047.png  icon_Paper_22_1059.png  icon_Paper_22_1071.png  icon_Paper_22_1083.png  icon_Paper_22_1095.png
icon_Paper_22_1000.png      icon_Paper_22_1012.png  icon_Paper_22_1024.png  icon_Paper_22_1036.png  icon_Paper_22_1048.png  icon_Paper_22_1060.png  icon_Paper_22_1072.png  icon_Paper_22_1084.png  icon_Paper_22_1096.png
icon_Paper_22_1001.png      icon_Paper_22_1013.png  icon_Paper_22_1025.png  icon_Paper_22_1037.png  icon_Paper_22_1049.png  icon_Paper_22_1061.png  icon_Paper_22_1073.png  icon_Paper_22_1085.png  icon_Paper_22_1097.png
icon_Paper_22_1002.png      icon_Paper_22_1014.png  icon_Paper_22_1026.png  icon_Paper_22_1038.png  icon_Paper_22_1050.png  icon_Paper_22_1062.png  icon_Paper_22_1074.png  icon_Paper_22_1086.png  icon_Paper_22_1098.png
icon_Paper_22_1003.png      icon_Paper_22_1015.png  icon_Paper_22_1027.png  icon_Paper_22_1039.png  icon_Paper_22_1051.png  icon_Paper_22_1063.png  icon_Paper_22_1075.png  icon_Paper_22_1087.png  icon_Paper_22_1099.png
icon_Paper_22_1004.png      icon_Paper_22_1016.png  icon_Paper_22_1028.png  icon_Paper_22_1040.png  icon_Paper_22_1052.png  icon_Paper_22_1064.png  icon_Paper_22_1076.png  icon_Paper_22_1088.png  icon_Paper_22_1.png
icon_Paper_22_1005.png      icon_Paper_22_1017.png  icon_Paper_22_1029.png  icon_Paper_22_1041.png  icon_Paper_22_1053.png  icon_Paper_22_1065.png  icon_Paper_22_1077.png  icon_Paper_22_1089.png  icon_Paper_22_7.png
icon_Paper_22_1006.png      icon_Paper_22_1018.png  icon_Paper_22_1030.png  icon_Paper_22_1042.png  icon_Paper_22_1054.png  icon_Paper_22_1066.png  icon_Paper_22_1078.png  icon_Paper_22_1090.png
icon_Paper_22_1007.png      icon_Paper_22_1019.png  icon_Paper_22_1031.png  icon_Paper_22_1043.png  icon_Paper_22_1055.png  icon_Paper_22_1067.png  icon_Paper_22_1079.png  icon_Paper_22_1091.png
icon_Paper_22_1008.png      icon_Paper_22_1020.png  icon_Paper_22_1032.png  icon_Paper_22_1044.png  icon_Paper_22_1056.png  icon_Paper_22_1068.png  icon_Paper_22_1080.png  icon_Paper_22_1092.png
icon_Paper_22_1009.png      icon_Paper_22_1021.png  icon_Paper_22_1033.png  icon_Paper_22_1045.png  icon_Paper_22_1057.png  icon_Paper_22_1069.png  icon_Paper_22_1081.png  icon_Paper_22_1093.png
```
Also, being 22x22 means those icons are too tiny for my HiDPI resolution.

And I'm missing the narrower notifications (with less height) from the static binaries version, but for now, I'm willing to continue testing the version built from source. Anyway, thanks.

**Comment by ilya-fedin** [comment]
> No tray menu ugly font in this version, so it seems to work well with XAppStatusIcon.

No, just built-from-source version can use system fonts


> Cleaning the icon cache didn't help, it's got recreated with the same blue icons in tray.

Hmm, this is very strange. Can you reproduce with -dynamic-bin package? Maybe it is an old version of system-tray-icon.patch in your aur helper cache...


> Also, being 22x22 means those icons are too tiny for my HiDPI resolution.

I can set bigger resolution, but it won't help you since Cinnamon hasn't support of StatusNotifierItem API.

**Comment by pioneer** [comment]
I have just reproduced it with the `-dynamic-bin` package, the same blue icons. What else can I do?
Also, what's interesting is that the `-dynamic-bin` package has proper fonts in the tray menu, and it's not built from source.

**Comment by ilya-fedin** [comment]
No, it's built from source with Arch's Qt on GitHub Actions

I think your icon theme has a `telegram-panel` icon with blue background, or your platform theme plugin returns a `telegram` icon instead of the `telegram-panel`. Anyway, it should look like this:
![изображение](https://user-images.githubusercontent.com/17829319/72723787-7f3ce400-3b79-11ea-8377-13863a69f59d.png)

Would be nice if you send a screenshot with icon and value of the `$QT_QPA_PLATFORMTHEME` variable

**Comment by pioneer** [comment]
The icons of my two Kotatograms look like this in tray:
![Выделение_023](https://user-images.githubusercontent.com/200538/73071786-5cce0200-3ebc-11ea-9eb6-6ffbfd1997ef.png)

The Qt platform theme is as below:
```
$ env | grep QT_QPA_PLATFORMTHEME
QT_QPA_PLATFORMTHEME=qt5ct
```
In `qt5ct` I have set up the `kvantum` theme. And in Kvantum Manager, there's `Materia` theme set up.

My icon theme is a bit customized [Paper theme](https://github.com/snwh/paper-icon-theme/tree/master/Paper), I've only added inheriting the [Papirus theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/master/Papirus) in case there's an icon missing, see below:
```
[Icon Theme]
Name=Paper
Comment=A simple and modern icon theme.
Inherits=Papirus,Adwaita,gnome,hicolor
Example=folder
```


This is what the Paper has:
```
[/usr/share/icons/Paper]$ find . | grep telegram
./Paper/24x24/web/unity-webapps-telegram.png
./Paper/24x24/web/telegram.png
./Paper/24x24/web/web-telegram.png
./Paper/32x32@2x/web/unity-webapps-telegram.png
./Paper/32x32@2x/web/telegram.png
./Paper/32x32@2x/web/web-telegram.png
./Paper/16x16/web/unity-webapps-telegram.png
./Paper/16x16/web/telegram.png
./Paper/16x16/web/web-telegram.png
./Paper/32x32/web/unity-webapps-telegram.png
./Paper/32x32/web/telegram.png
./Paper/32x32/web/web-telegram.png
./Paper/512x512@2x/web/unity-webapps-telegram.png
./Paper/512x512@2x/web/telegram.png
./Paper/512x512@2x/web/web-telegram.png
./Paper/48x48/web/unity-webapps-telegram.png
./Paper/48x48/web/telegram.png
./Paper/48x48/web/web-telegram.png
./Paper/512x512/web/unity-webapps-telegram.png
./Paper/512x512/web/telegram.png
./Paper/512x512/web/web-telegram.png
./Paper/16x16@2x/web/unity-webapps-telegram.png
./Paper/16x16@2x/web/telegram.png
./Paper/16x16@2x/web/web-telegram.png
./Paper/24x24@2x/web/unity-webapps-telegram.png
./Paper/24x24@2x/web/telegram.png
./Paper/24x24@2x/web/web-telegram.png
./Paper/48x48@2x/web/unity-webapps-telegram.png
./Paper/48x48@2x/web/telegram.png
./Paper/48x48@2x/web/web-telegram.png
```
This is for the Papirus:
```
[/usr/share/icons/Papirus]$ find . | grep telegram
./22x22/apps/telegram-desktop.svg
./22x22/apps/org.telegram.desktop.svg
./22x22/apps/telegram.svg
./22x22/panel/telegram-mute-panel.svg
./22x22/panel/telegram-panel.svg
./22x22/panel/telegram-attention-panel.svg
./24x24/apps/telegram-desktop.svg
./24x24/apps/org.telegram.desktop.svg
./24x24/apps/telegram.svg
./24x24/panel/telegram-mute-panel.svg
./24x24/panel/telegram-panel.svg
./24x24/panel/telegram-attention-panel.svg
./16x16/apps/telegram-desktop.svg
./16x16/apps/org.telegram.desktop.svg
./16x16/apps/telegram.svg
./16x16/panel/telegram-mute-panel.svg
./16x16/panel/telegram-panel.svg
./16x16/panel/telegram-attention-panel.svg
./32x32/apps/telegram-desktop.svg
./32x32/apps/org.telegram.desktop.svg
./32x32/apps/telegram.svg
./48x48/apps/telegram-desktop.svg
./48x48/apps/org.telegram.desktop.svg
./48x48/apps/telegram.svg
./64x64/apps/telegram-desktop.svg
./64x64/apps/org.telegram.desktop.svg
./64x64/apps/telegram.svg
```

The icon in my tray is looking like this icon - https://github.com/snwh/paper-icon-theme/blob/master/Paper/16x16/web/web-telegram.png, but I'm not sure if it's actually this one or it's taken from somewhere else. The Papirus theme has the same 16x16 icon but in SVG, and I doubt it's an SVG in my tray. Anyway, all the icons you can check on the Paper and Papirus repos mentioned above. Hope the above helps.

**Comment by pioneer** [comment]
Also, with the recent Kotatogram built from source, I'm seeing again the bug with clicking on a notification and not opening the proper chat. Unfortunately, this is happening even when I click on the small arrow in a notification.

**Comment by ilya-fedin** [comment]
> The icon in my tray is looking like this icon - https://github.com/snwh/paper-icon-theme/blob/master/Paper/16x16/web/web-telegram.png

Oh... Any way, I can't fix this, since the logic of icon choosing is in platformtheme plugin (qt5ct in your case).
I can request kotatogram-*-panel, this fix the issue, but the patch will become useless, since no one of icon theme creators cares about kotatogram.

**Comment by pioneer** [comment]
From what I see, app developers tend to add icons to the `hicolor` theme, not sure if it can help in this case. Do you know why the other icons in my tray are rendered properly?

**Comment by ilya-fedin** [comment]
> From what I see, app developers tend to add icons to the `hicolor` theme

My patch adds using of system theme icons, it should look for current theme, not hicolor


> Do you know why the other icons in my tray are rendered properly?

Because
1. They're not a unpopular fork and they don't choose between a proper icon and a icon from system theme
2. They don't need post-processing of the icon because they don't have a message counter

**Comment by ilya-fedin** [comment]
> Also, with the recent Kotatogram built from source, I'm seeing again the bug with clicking on a notification and not opening the proper chat. Unfortunately, this is happening even when I click on the small arrow in a notification.

btw, that code reached upstream at v1.9.3, so you should have the same problems with the static binary and tdesktop

**Comment by pioneer** [comment]
> I can request kotatogram-*-panel, this fix the issue, but the patch will become useless, since no one of icon theme creators care about kotatogram.
Well, maybe in a distribution package you can provide your own icons?

**Comment by ilya-fedin** [comment]
> Well, maybe in a distribution package you can provide your own icons?

> My patch adds using of system theme icons, it should look for current theme, not hicolor

**Comment by pioneer** [comment]
So, you're intentionally using the system Telegram icons instead of Kotatogram's own? I'm not against that, just curious about the idea behind.

**Comment by pioneer** [comment]
Just have tested a bit the upstream Telegram 1.9.8, seems the issue with notification clicking is gone now.

**Comment by ilya-fedin** [comment]
> So, you're intentionally using the system Telegram icons instead of Kotatogram's own? I'm not against that, just curious about the idea behind.

Yes, so that the icon is [in one style](https://user-images.githubusercontent.com/17829319/72723787-7f3ce400-3b79-11ea-8377-13863a69f59d.png) with others
