### ISSUE TITLE
The captions under the folder icons do not fit.

### ISSUE THREAD

**Issue by bravo321** [kotatogram/kotatogram-desktop#31]
![bug](https://user-images.githubusercontent.com/26696732/80305795-d03b2480-87c7-11ea-906e-457f716b7d8a.png)
Ubuntu 18.04.4 LTS ; Gnome 3.28.4; Version 1.3 (TD 2.1)

**Comment by RadRussianRus** [comment]
Known , will be fixed in 1.3.1.

**Comment by RadRussianRus** [comment]
Should be fixed in 1.3.1, please, update.
