### ISSUE TITLE
Failed to compile in Mac: Reference to local binding 'flag' declared 

### ISSUE THREAD

**Issue by DaviSMoura** [kotatogram/kotatogram-desktop#320]
Hi! Im trying to compile Kotatogram in my Macbook (its my first time using mac haha).
But, Xcode show this error:

```
Showing Recent Issues
/Users/davimoura/Documents/Codes/kotatogram/kotatogram-desktop/Telegram/SourceFiles/data/data_chat_filters.cpp:180:21: Reference to local binding 'flag' declared in enclosing function 'Data::MakeLocalFolder'
```

<img src="https://i.imgur.com/Xqmdp2o.png" />

My PC is a Macbook Pro 2021 (M1 Pro)

Note: Ive compiled the same code in a Linux env and I had no problems

**Comment by ilya-fedin** [comment]
From which commit are you trying to build? If you're trying the dev branch, you can see it doesn't build even at macOS CI.

**Comment by DaviSMoura** [comment]
@ilya-fedin Thanks for answering :)

Actually, Ive tried to compile with dev and master but no success in both.
Trying in master, the error is before compiling, in configure step:

<img src="https://i.imgur.com/PObKUnW.png" />

**Comment by ilya-fedin** [comment]
AFAIK building on arm64 hardware is broken, yeah, you should find an amd64 hardware

**Comment by DaviSMoura** [comment]
Sorry for idiot question, but: I can build for arm64 in a amd64 hardware?

**Comment by ilya-fedin** [comment]
Yeah, since another way around is not tested by tdesktop itself

**Comment by DaviSMoura** [comment]
Hmmm. ok.

Thanks for answering 
Have a great day, bro. :)
