### ISSUE TITLE
This message is not supported

### ISSUE THREAD

**Issue by xiaochency** [kotatogram/kotatogram-desktop#328]
### Steps to reproduce

This message is not supported by your version of Kotatogram Desktop. Please update to the latest version in Settings, or install it from https://kotatogram.github.io
![简单图床 - EasyImage](https://laji.o--o.xyz/i/2022/03/07/ug4ige.jpg)

### Expected behaviour

N/A

### Actual behaviour

N/A

### Operating system

Windows 10

### Version of Kotatogram Desktop

1.4.8 x64(TD 3.3)

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
#289
