### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by l29** [kotatogram/kotatogram-desktop#336]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Since this feature already exists for other telegram forks I wanted to ask if it would be possible to add it for kotatogram as well.

Option:
Starting a secret chat

And a more advanced option would be that you can set in the kotatogram settings that all private chats you open are automatically secret chats if that is possible.

### Describe alternatives you've considered

 Just the option to open a secret chat

**Comment by RememberTheAir** [comment]
#8
