### ISSUE TITLE
[Feature Request] Menu item for adding chats to folders

### ISSUE THREAD

**Issue by ghost** [kotatogram/kotatogram-desktop#342]
### Is your feature request related to a problem?

If you have a lot of chats, adding them to folders can be a bit of a problem.

### Describe the solution you'd like

it would be nice if there was a menu item for adding chats to folders. 

Right click to chat
select "add to folder"
choose which folders you want the chat to be added to (submenu or a new window)

[x] folder a
[ ] folder b
[x] folder c

### Describe alternatives you've considered

N/A

**Comment by elvisef** [comment]
Yep, I have the same problem. This should be working exactly like here (in Telegram):
![jcfxMwJbIM](https://github.com/kotatogram/kotatogram-desktop/assets/25976749/31c7fed9-a4bf-47b0-87ea-1ddc8944490a)

Anyway, why was this menu item removed ?
It's really crucial I think.
There could be an option to "enable/disable" this item but should be available.
Really, I don't understand it is not here...

Isn't Kotatogram a clone of Telegram with some changes ?

**Comment by EricKotato** [comment]
@elvisef Kotatogram Desktop is based on older TDesktop version, this menu was implemented later.

**Comment by EricKotato** [comment]
BTW, since this is implemented in TDesktop, I'm closing it, as it will arrive as soon as Kotatogram is updated. See #420.
