### ISSUE TITLE
Kotatogram can't display animated stickers.

### ISSUE THREAD

**Issue by TechnoMasterBoy** [kotatogram/kotatogram-desktop#345]
### Steps to reproduce

Title pretty much. Someone sent an animated sticker in chat and Kotatogram just says this:
This message is not supported by your version of Kotatogram Desktop. Please update to the latest version in Settings, or install it from https://kotatogram.github.io
Even though I have the latest version.

It only happens with some stickers, like this pack: https://t.me/addstickers/Test_464322314
This one works completely fine: https://t.me/addstickers/More_Capoo
It seems like most sticker packs works, just a few random ones that don't. I tested 6 others and no issues.

### Expected behaviour

It should show the animated sticker. It works in standard Telegram app 3.6.1 x64.

### Actual behaviour

Animated sticker did not show, it instead showed error message, telling me to update.

### Operating system

Windows 10 Home. 64 bit. Version 21H1. OS Build 19043.1586 Windows Feature Experience Pack 120.2212.4170.0

### Version of Kotatogram Desktop

1.4.8 x64 (TD 3.3) which is the latest right now.

### Installation source

Static binary from official website

**Comment by TechnoMasterBoy** [comment]
Another sticker pack that don't work with Kotatogram for some reason:
https://t.me/addstickers/video1840033944_by_CrimsonMeguBot

**Comment by EricKotato** [comment]
Works on 1.4.9 beta.
