### ISSUE TITLE
Can't login without mobile phone

### ISSUE THREAD

**Issue by SkybuckFlying** [kotatogram/kotatogram-desktop#347]
### Steps to reproduce

Same issue as telegram.

### Expected behaviour

x

### Actual behaviour

x

Useless fork.

### Operating system

Windows 7

### Version of Kotatogram Desktop

1.4.8

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
> Useless fork.

What do you expect kotatogram to do, exactly? This is a Telegram issue, third-party clients can't do much about it. The server decides whether to send the sms or not

**Comment by EricKotato** [comment]
Also "login without mobile phone" never was a Kotatogram-specific feature. It just worked for some time, but now it doesn't (which was expected, actually). You can try to use custom API ID and hash, but there is no guarantee it will work as expected.
