### ISSUE TITLE
[Question] Disable or blur GIF ?

### ISSUE THREAD

**Issue by graysuit** [kotatogram/kotatogram-desktop#349]
Is it possible to disable media or either make it blur and don't autoplay ? 
Because many content are NSFW (not safe for work).
If possible, then which settings do I change ?

I reviewed settings, nothing that i found relevant.

**Comment by ilya-fedin** [comment]
Advanced -> Automatic media download

**Comment by graysuit** [comment]
SOLVED ! Thanks @ilya-fedin 

Leaving an screenshot, may be helpful for others.
![Capture](https://user-images.githubusercontent.com/54432616/164989193-efc7eda8-55a5-48d4-a8aa-932f9c806f31.PNG)
