### ISSUE TITLE
Got a user that by existing makes kotatogram bug out

### ISSUE THREAD

**Issue by TheK0tYaRa** [kotatogram/kotatogram-desktop#351]
### Steps to reproduce

1. Find any message from Kobbina Bapa by UserID 807542564 (they are available in @Python telegram group, no join required)
2. Click on context menu button "User Messages"

### Expected behaviour

Specific user's messages are listed on the left list

### Actual behaviour

Messages of all the users are in the list while the "From: Kobbina Bapa" is present.

### Operating system

Archlinux

### Version of Kotatogram Desktop

1.4.9 beta (TD 3.5.2)

### Installation source

Other (unofficial) source

**Comment by TheK0tYaRa** [comment]
The aur package is `kotatogram-desktop-beta-dynamic-bin`

**Comment by TheK0tYaRa** [comment]
The same user's avatar is not openable via clicking

**Comment by EricKotato** [comment]
Works fine for me on `kotatogram-desktop-beta` AUR package. Maybe it's package-specific?

**Comment by TheK0tYaRa** [comment]
It's a binary package in my case after all so i don't think it should have such issues.

**Comment by TheK0tYaRa** [comment]
![image](https://user-images.githubusercontent.com/27967034/166678479-827b3480-6749-41bc-bd9b-1f5a298915e5.png)
o shi
Imma try static binary, it's hella weird

**Comment by TheK0tYaRa** [comment]
And after just restarting it's fine again... I'm going to blame archlinux or my configs at that point, i guess. Also the kotatogram-desktop-beta failed to build.

**Comment by ilya-fedin** [comment]
Well, tdesktop's MTProto implementation is not bugless, so various bugs like "impossible to load images" or "impossible to get user's messages" are ok with long application uptime

**Comment by TheK0tYaRa** [comment]
So it's an issue of prolonged usage?

**Comment by ilya-fedin** [comment]
Most likely
