### ISSUE TITLE
[Feature Request] Anti-Revoke

### ISSUE THREAD

**Issue by 0x416e6f6e** [kotatogram/kotatogram-desktop#354]
### Is your feature request related to a problem?

Sometimes messages are deleted (by the sender or moderator) right at the moment of reading. This is very annoying and makes communication baffling.

### Describe the solution you'd like

To store received messages locally, and if they are revoked, do not delete them, but only mark them as revoked.

### Describe alternatives you've considered

-

### Additional context

This feature has been implemented by [Telegram-Anti-Revoke](https://github.com/SpriteOvO/Telegram-Anti-Revoke) plugin, but the project has been abandoned and is no longer maintained. Perhaps it can be taken as a basis for further development.

**Comment by EricKotato** [comment]
It's against Telegram API Terms of Service, so it won't be implemented.
https://kotatogram.github.io/faq/#ghost-mode
