### ISSUE TITLE
[Feature Request] Way to show user's registration date? 

### ISSUE THREAD

**Issue by hkfsc** [kotatogram/kotatogram-desktop#359]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I know its not possible with official API, but we can find other ways like invoking the Bot API which already collection the info for us, or check Nicegram IOS version, it also provided this function, will be nice if we can have this feature.

### Describe alternatives you've considered

Nothing

**Comment by EricKotato** [comment]
There is no way to get exact registration date and time. Bots who show that use data about when ID pool was started (which was collected beforehand AFAIK).

**Comment by hkfsc** [comment]
> There is no way to get exact registration date and time. Bots who show that use data about when ID pool was started (which was collected beforehand AFAIK).

Yes, they are collected by bots or clients, and I know Nicegram must have a database to store those information, otherwise we can't know the registration date of users, it can be a function which might help users avoid fraud(If someone use a new account to contact you, we should be more careful when they asking your money). I hope you can consider this later, thanks!
