### ISSUE TITLE
[Feature Request] Go to first message button

### ISSUE THREAD

**Issue by abdo2048** [kotatogram/kotatogram-desktop#365]
### Is your feature request related to a problem?

NO

### Describe the solution you'd like

A button called "Go to first message" to navigate me to the first message in chats, groups, bots and channels.

### Describe alternatives you've considered

Nothing

### Additional context

![YyyP7N4ARx](https://user-images.githubusercontent.com/26915383/170898053-82fbba01-53de-4b86-9118-0c8c8b201e04.png)

**Comment by EricKotato** [comment]
It's already implemented.
![](https://user-images.githubusercontent.com/2903496/170930672-08c38ac8-3bb7-4119-a150-3a710eb2c6e8.png)
Press Ctrl+J in chat or click on date (not time, date) to see this window.

**Comment by abdo2048** [comment]
Thank you, I was on Version 1.4.8 (TD 3.3), so I downloaded Version 1.4.9 beta (TD 3.5.2) and found it now.
