### ISSUE TITLE
Missing font size slider

### ISSUE THREAD

**Issue by Technetium1** [kotatogram/kotatogram-desktop#368]
### Steps to reproduce

1. Try to adjust the font size
2. Fail 

### Expected behaviour

Should have a slider to adjust font size: 
![image](https://user-images.githubusercontent.com/9877150/172058111-c17bdd19-c56e-44f6-b8ab-6fb499d4b443.png)

### Actual behaviour

The slider does not exist

### Operating system

Doesn't matter

### Version of Kotatogram Desktop

1.4.9 beta (TD 3.5.2)

### Installation source

Other (unofficial) source

### Logs

Not required.
Maybe something to do with: https://github.com/kotatogram/kotatogram-desktop/pull/177

**Comment by EricKotato** [comment]
It's not missing.
![](https://user-images.githubusercontent.com/2903496/172058231-b6e39401-edb9-4f5a-a8e3-abe27246a432.png)

See Settings > Kotatogram Settings > Change application fonts > scroll to bottom.

**Comment by Technetium1** [comment]
Great, I didn't realize they were buried that deep, thank you.
