### ISSUE TITLE
[Feature Request] Vim keybindings

### ISSUE THREAD

**Issue by guillaumeboehm** [kotatogram/kotatogram-desktop#371]
### Is your feature request related to a problem?

Telegram doesn't support shortcuts configuration.

### Describe the solution you'd like

I want to be able to scroll through messages using shortcuts:

Alt+k - scroll up a little (slow)
Alt+j - scroll down a little (slow)
Alt+u - scroll half-screen up (fast)
Alt+d - scroll half-screen down (fast)
Alt+b - scroll screen up (day wise scroll, very fast)
Alt+f - scroll screen down (day wise scroll, very fast)
Maybe also Ctrl+e/Ctrl+y (or Alt) - interchangeable with Alt+j/Alt+k
I suggest using Alt key since Ctrl+k, Ctrl+j, Ctrl+f are already mapped to some actions.

### Describe alternatives you've considered

Keyboard navigation is of course possible but clearly not ideal at the moment.

### Additional context

This is a copy of this issue on the official telegram repo, https://github.com/telegramdesktop/tdesktop/issues/16300. But I am using kotatogram now, and I am kind of hoping that this team is more receptive to this feature.

I would be glad to work on this issue, but I'd at least like to know how viable it is before diving into a new project.

**Comment by ilya-fedin** [comment]
> But I am using kotatogram now, and I am kind of hoping that this team is more receptive to this feature.

Well, no one rejected your feature in tdesktop, I just think that they don't have time to implement that. I'm not sure that we have though given that the project is suspended.

**Comment by guillaumeboehm** [comment]
I see, you've got a point if I want to help I should probably do it on tdesktop. Very quickly as you seem responsive, what do you think about the feasability?

**Comment by ilya-fedin** [comment]
Well, tdesktop already have shortcuts config, you can create a PR that adds new shortcuts to it apparently. You should probably ask preston at tdesktop repo to see how he sees that implemented. He rarely reads GitHub though, so maybe you would need to reach him at Telegram...

**Comment by guillaumeboehm** [comment]
Alright! Thanks a lot for the responses, I'll look around.
