### ISSUE TITLE
[Feature Request] Save / Forward restricted content group and channel

### ISSUE THREAD

**Issue by siwant123** [kotatogram/kotatogram-desktop#372]
### Is your feature request related to a problem?

is there a way to save restricted content on channel or group , if this feature is in the kotatogram it will be very useful.

### Describe the solution you'd like

is there a way to save restricted content on channel or group , if this feature is in the kotatogram it will be very useful.

### Describe alternatives you've considered

is there a way to save restricted content on channel or group , if this feature is in the kotatogram it will be very useful.

**Comment by EricKotato** [comment]
It won't be implemented since it's against Telegram API Terms of Service.
