### ISSUE TITLE
[Question] приложение не поддерживает telegram premium

### ISSUE THREAD

**Issue by yo8z6gv** [kotatogram/kotatogram-desktop#373]
на странице https://t.me/premium
"Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке https://kotatogram.github.io"

закидывая файл превышающий 2 гб пишет ошибку о превышении лимита, тогда как в официальном приложении такой ошибки нет..
такие сообщения не отображаются

**Comment by EricKotato** [comment]
Это функция TDesktop, поэтому она прибудет с обновлением. На вопрос "когда обновление" ответ есть в #120.
