### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ghost** [kotatogram/kotatogram-desktop#377]
### Is your feature request related to a problem?

telegram premium version

### Describe the solution you'd like

files with 3/4GB being said as not compatible with kotatogram, I believe it is by the new telegram premium

### Describe alternatives you've considered

I believe that looking for a way to use the same telegram desktop function to have access to these files

**Comment by EricKotato** [comment]
It will be supported after source code update, which happens almost every update. Please be patient.
