### ISSUE TITLE
[Feature Request]  Hide messages from blocked users in group chats.

### ISSUE THREAD

**Issue by hkfsc** [kotatogram/kotatogram-desktop#378]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

https://github.com/kotatogram/kotatogram-desktop/issues/17#issuecomment-672982937
They already bring it back to the neko app!
Could you consider add it now?

### Describe alternatives you've considered

N

**Comment by EricKotato** [comment]
They bring it back not because it's allowed now, they just confronting Telegram. I don't want confrontation with Telegram, so no.
