### ISSUE TITLE
[Feature Request] Increase file size to 4GB

### ISSUE THREAD

**Issue by wwr97925** [kotatogram/kotatogram-desktop#380]
### Is your feature request related to a problem?

The upload size limit for premium member has been increased to 4GB, but uploads of files over 2GB are still prohibited. Files over 2GB are also not available.

### Describe the solution you'd like

Increase file size limit to 4GB

### Describe alternatives you've considered

N

### Additional context

Thanks!

**Comment by EricKotato** [comment]
It will be supported after source code update, which happens almost every update. Please be patient.

BTW, it's a duplicate of #377.
