### ISSUE TITLE
Account Banning on Linux 

### ISSUE THREAD

**Issue by Yimellovzski** [kotatogram/kotatogram-desktop#383]
### Steps to reproduce

1. Log in to any account.
2. Enter the verification code.
3. ????
4. Account Banned permanently.

### Expected behaviour

It should not instantly ban me the moment I sign in..?

### Actual behaviour

......

### Operating system

Linux Pop!_OS 22.04

### Version of Kotatogram Desktop

1.4.8, the same I used on windows before switching operating system.

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
See: https://kotatogram.github.io/faq/#alt-client-bans

In short: I can't do anything about it. Try to write to login@stel.com or recover@telegram.org to get your account back.
