### ISSUE TITLE
[Feature Request] go to the first message in chat

### ISSUE THREAD

**Issue by passthesh3ll** [kotatogram/kotatogram-desktop#385]
### Is your feature request related to a problem?

Go to the first message in a chat

### Describe the solution you'd like

add a menu option to go to the first message in a chat

### Describe alternatives you've considered

/dev/null

### Additional context

/dev/null

**Comment by EricKotato** [comment]
It's already implemented in 1.4.9 beta.
![](https://user-images.githubusercontent.com/2903496/186996274-6f414aef-193e-4628-960a-0dd2f5b5f3c4.png)
Click on date bubble or press `Ctrl+H`, then click on three dots button and select "Jump to beginning".
