### ISSUE TITLE
[Feature Request] Remove sponsored ads in channels

### ISSUE THREAD

**Issue by liao-andy** [kotatogram/kotatogram-desktop#392]
### Is your feature request related to a problem?

Right now when using Kotatogram 1.4.9 for Mac, sponsored ads on public channels >1k subscribers appear. When you scroll down the last message you will see an ad pop up. Not only is this an annoyance, but many of the ads are cryptocurrency related which put the user at risk since they are fishy and scam.

<img width="452" alt="Telegram ads" src="https://user-images.githubusercontent.com/61610201/189381015-446ba834-1502-413c-a491-25c242ceb391.png">

Above is an example.

### Describe the solution you'd like

I will like Kotatogram to, regardless if the user has premium, not fetch these sponsored ads or not display them. Since these sponsored messages have a "sponsored" tag I don't think it's hard to distinguish from normal messages.

### Describe alternatives you've considered

If these ads are to be kept, another solution is to add a toggle in Telegram settings to turn sponsored messages on and off so users can choose

**Comment by EricKotato** [comment]
Quoting https://core.telegram.org/api/sponsored-messages#sponsored-messages-in-third-party-apps:
> If their app allows its users to access content from Telegram channels, third-party developers using the Telegram API are required to support and properly display official sponsored messages in their apps by January 1, 2022. Unfortunately, Telegram cannot financially sustain third-party apps that do not display sponsored messages and they will have to be disconnected. 

"support and properly display" is Telegram's requirement.
