### ISSUE TITLE
Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке

### ISSUE THREAD

**Issue by als-creator** [kotatogram/kotatogram-desktop#394]
### Steps to reproduce

Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке

### Expected behaviour

Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке

### Actual behaviour

Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке

### Operating system

Linux

### Version of Kotatogram Desktop

1.4.9 beta

### Installation source

Other (unofficial) source

### Logs

```shell
текущий репозиторий дистрибутива, версии котатограм дев или текущая
проблема всех версий
в чатах высказали предположение что эта проблема с отображением сообщений возникает из за хэштэгов в постах, можно ли как то опционально добавить обработку таких сообщений для нормального отображения?
```

**Comment by EricKotato** [comment]
Они будут поддерживаться, когда произойдёт обновление исходников TDesktop, а это происходит почти каждый апдейт.
