### ISSUE TITLE
Kotatogram is crashing in Unity

### ISSUE THREAD

**Issue by dayfuaim** [kotatogram/kotatogram-desktop#395]
### Steps to reproduce

1. Install Ubuntu Unity desktop.
2. Log into Unity.
3. Start Kotatogram.

### Expected behaviour

Kotatogram *does* start in Unity.

### Actual behaviour

Kotatogram crashes (see log).

I guess it's because `XDG_SESSION_TYPE=x11` in Unity (instead of `wayland`). 

### Operating system

Ubuntu 22.10 beta

### Version of Kotatogram Desktop

1.4.9 beta

### Installation source

Static binary from official website

### Logs

```shell
[~]% ./Kotatogram/Kotatogram.AppImage
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, xcb.

[1]    137217 IOT instruction (core dumped)  ./Kotatogram/Kotatogram.AppImage
```

**Comment by ilya-fedin** [comment]
> I guess it's because `XDG_SESSION_TYPE=x11` in Unity (instead of `wayland`).

It would rather be if it was `XDG_SESSION_TYPE=wayland`. It may also because you have `QT_QPA_PLATFORM=wayland`

**Comment by dayfuaim** [comment]
Yes, it is (`QT_QPA_PLATFORM`).
I put
```
QT_QPA_PLATFORM=xcb ./Kotatogram/Kotatogram.AppImage
```
and Kotatogram started.

Could it be done in some way internally?
I mean choosing from wayland or x11.

**Comment by ilya-fedin** [comment]
> Could it be done in some way internally?

What do you mean by 'internally'?

**Comment by dayfuaim** [comment]
> > Could it be done in some way internally?
> 
> What do you mean by 'internally'?

I mean it's happening after I started the app by itself, not by me putting `QT_QPA_...` in command line.
_Application_ determines which environment it was started in.

**Comment by ilya-fedin** [comment]
> _Application_ determines which environment it was started in.

No, it's the user and system who determines the environment

**Comment by dayfuaim** [comment]
OK. Got it. :)
