### ISSUE TITLE
[Feature Request] Option to disable emoji panal on hover

### ISSUE THREAD

**Issue by stickynoteme** [kotatogram/kotatogram-desktop#397]
### Is your feature request related to a problem?

Not a problem just an annoyance.

### Describe the solution you'd like

An option that disables hover showing the emoji panel.

### Describe alternatives you've considered

An option to disable the emoji button. 
realistically I use Win+; and use the built in emoji picker any time I actually use them because it's universal and it's what my fingers go to. 

### Additional context

The auto show on hover emoji panel in telegram has been driving me batty since the very first time I used telegram back in 2015, and in the 7 years I've used it daily I've yet to get used to it being annoying, so I thought I'd finally come and make a request at someplace that might actually fix it.

**Comment by EricKotato** [comment]
It's already implemented. 1.4.8 has "Emoji panel on hover" option in Kotatogram Settings. In 1.4.9 this option was moved in TDesktop experimental settings (Settings > Advanced > Experimental Settings > Show tabbet panel by click) since it was implemented in TDesktop.
