### ISSUE TITLE
[Feature Request] custom systray icon

### ISSUE THREAD

**Issue by drzraf** [kotatogram/kotatogram-desktop#398]
### Is your feature request related to a problem?

I often have two instances of kotatogram running simultaneously using two distinct profile directories. I can't recognize which one I want to maximize because the systray icons are identical.

### Describe the solution you'd like

Customizable systray icons (on Gnome/Wayland)

### Describe alternatives you've considered

On XDG-compatible desktop, a systray icon can appear differently if there are notification (or show a little number of unread messages), the same system could be used to define a color-flavor (eg: based on the UI-color for example).

### Additional context

It may need some custom `.desktop` or similar XDG installation files... or not... depending on the OS and WM capabilities.

**Comment by EricKotato** [comment]
It's already implemented.
You can choose a predefined tray icon in Kotatogram Settings or you can put `icon.png` file in your `tdata` folder.

**Comment by drzraf** [comment]
I missed this option in the settings !


![Screenshot from 2022-10-20 22-57-26](https://user-images.githubusercontent.com/1169926/197093152-4dbc9478-d7ce-4fee-8ecb-86b9bd97614f.png)


Really sorry!
