### ISSUE TITLE
[Feature Request] PinnedDialogsCountMax

### ISSUE THREAD

**Issue by merl111** [kotatogram/kotatogram-desktop#4]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Increase PinnedDialogsCountMax or make it configurable

### Additional context
Currently one can pin 5 chats maximum, depending on how many chats one has this might be too less.

**Comment by RadRussianRus** [comment]
Since pins are server-side, it could mix and cause all sorts of troubles. I'll try to find an alternative way though.

**Comment by merl111** [comment]
I see, what about favourites? like I can tag a chat as favourite and it’s then shown in a seperate tab?  There was another alternative Telegram client, called Bettergram, it had different tabs that split up, groups, channels, private chats and favourites, that was very convenient.

**Comment by RadRussianRus** [comment]
Well, horizontal tabs using horizontal space which doesn't fit for TDesktop, since you can minimze sidebar up to profile pic column. So only options here are:

* Pins (or something similar)
* Collapsible lists (like workmode)
* Folders (like archive)

Other options could really look ugly.

**Comment by jemito131517** [comment]
> Since pins are server-side, it could mix and cause all sorts of troubles. I'll try to find an alternative way though.

Ok

**Comment by c-cesar** [comment]
Telegram for MacOS have configurable tabs, and I don't think it's ugly.

https://engnews24h.com/how-to-enable-tabs-for-sorting-chats-in-telegram-beta-on-macos/

**Comment by RadRussianRus** [comment]
Since it has cloud sync, it should be added in Telegram natively.

Still:
> Well, horizontal tabs using horizontal space which doesn't fit for TDesktop, since you can minimze sidebar up to profile pic column.

Maybe TDesktop developer will find a way to fit tabs, but I still think that folders or drop-down lists are better.

But for now we should wait until release, I think.

**Comment by RadRussianRus** [comment]
Since the official release of chat folders with 100 pins per folder I think this issue is no longer relevant.
