### ISSUE TITLE
Incorrect restriction on account phone number

### ISSUE THREAD

**Issue by j-ds-au** [kotatogram/kotatogram-desktop#404]
### Steps to reproduce

Start application (I used portable 32 bit)
Select Australia for the +61 country prefix
Try selecting 2 as the next digit
You are informed that the number is invalid 

### Expected behaviour

Telegram allows accounts that are linked to landline telephone numbers, not just mobile numbers, so this desktop app needs to also accept such numbers.

### Actual behaviour

Only mobile telephone numbers are accepted by this app.

### Operating system

MS Windows 10, 64 bit

### Version of Kotatogram Desktop

1.4.8 Portable 32 bit

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
How would you accept SMS on it?

**Comment by j-ds-au** [comment]
Telegram sends codes as a voice message to landline numbers.

**Comment by EricKotato** [comment]
This should be done in TDesktop first.

Please test it on latest Telegram Desktop (currently it's 4.3.2). If it works, then Kotatogram will support it after source code update.

If it doesn't work, search an issue in [TDesktop's repo](https://github.com/telegramdesktop/tdesktop/issues) and if there is none, [open a new issue](https://github.com/telegramdesktop/tdesktop/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml).

If your issue will be rejected, feel free to reopen this issue or create a new one.
