### ISSUE TITLE
[Question] kotatogram login to telegram account problem，Please help with this

### ISSUE THREAD

**Issue by xp-repo** [kotatogram/kotatogram-desktop#406]
Hi: I logged in to the kotatogram using a telegram account, and all the groups and contacts I had joined were missing.

**Comment by xp-repo** [comment]
I have a lot of contacts on telegram, but I have none at kotatogram. Then I got the same problem when I used the verification code on kotatogram to log in to telegram. There was no contact or grouping

**Comment by EricKotato** [comment]
Does it happen in other Telegram clients?
The thing is, since Kotatogram fetches dialogs from Telegram API without maintaining local cache, it depends on server if chat will be fetched or not. If server doesn't send you chat list, I'm not sure how I can help here.

**Comment by xp-repo** [comment]
OK, Thanks for you.
