### ISSUE TITLE
[Question] Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке https://kotatogram.github.io

### ISSUE THREAD

**Issue by K14Mua** [kotatogram/kotatogram-desktop#413]
How many years do we have to wait for a software update? I'm fed up that every second message in the newsfeed I CAN'T READ. When was the last update? December 31, 2021? Congratulations! The author put a dick on the program for a WHOLE YEAR. If the application is abandoned, then tell me there! STOP LYING TO PEOPLE!

**Comment by EricKotato** [comment]
Your screams won't bring update any closer. See #408 and many others.
