### ISSUE TITLE
Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке https://kotatogram.github.io

### ISSUE THREAD

**Issue by sova32** [kotatogram/kotatogram-desktop#414]
### Steps to reproduce

in half of all messages in any chats and groups and in channels i see this:
Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке https://kotatogram.github.io

### Expected behaviour

Это сообщение не поддерживается в вашей версии Kotatogram. Пожалуйста, обновитесь до последней версии через Настройки или установите её по ссылке https://kotatogram.github.io

### Actual behaviour

https://i.imgur.com/VEwH7r2.png
https://i.imgur.com/OxXhXcZ.png

### Operating system

Operating System: Garuda Linux KDE Plasma Version: 5.26.4 KDE Frameworks Version: 5.101.0 Qt Version: 5.15.7 Kernel Version: 6.1.1-zen1-1-zen (64-bit) Graphics Platform: X11 Processors: 2 × AMD A4-6300 APU with Radeon(tm) HD Graphics Memory: 13.6 ГиБ of RAM Graphics Processor: AMD ARUBA

### Version of Kotatogram Desktop

1.4.8 and 1.4.9 downloaded from your site! not from my linux repo!

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
See #399 and many others.
