### ISSUE TITLE
[Feature Request] Topics support?

### ISSUE THREAD

**Issue by gianmarcogg03** [kotatogram/kotatogram-desktop#417]
### Is your feature request related to a problem?

When opening a chat that's supposed to be divided into topics it has everything mixed up and with incompatible messages.

### Describe the solution you'd like

Implement topics just like the standard Telegram Desktop.

### Describe alternatives you've considered

Leaving it as is and having messy chats.

**Comment by EricKotato** [comment]
Since it's implemented in TDesktop, it will arrive in Kotatogram in next update.
