### ISSUE TITLE
There is not "save selected" button  at messages panel.

### ISSUE THREAD

**Issue by acodervic** [kotatogram/kotatogram-desktop#418]
![image](https://user-images.githubusercontent.com/57204004/212259933-77d23f3e-30cb-471e-9e6a-8f3319a5fc28.png)

I can use this button download selected images/videos in office Telegram desktop.

Please add "save selected"  button .

**Comment by RememberTheAir** [comment]
This feature was introduced in a recent version of Telegram Desktop, it will eventually become available once kotatogram syncs with upstream

**Comment by acodervic** [comment]
> This feature was introduced in a recent version of Telegram Desktop, it will eventually become available once kotatogram syncs with upstream

thanks ! , is very useful

**Comment by EricKotato** [comment]
Since it's implemented in TDesktop, it will arrive once Kotatogram will be updated.
