### ISSUE TITLE
This message is not supported by your version of Kotatogram Desktop

### ISSUE THREAD

**Issue by NoahBK** [kotatogram/kotatogram-desktop#419]
### Steps to reproduce

Upload parts files/volumes from 7zip as seen [here.](https://i.imgur.com/2fVO7JG.png)

The file upload still works, it just doesn't show the files or give me the option to download/view files as seen [here.](https://i.imgur.com/t3Krr6F.png)

### Expected behaviour

The files should so as they normal do in the actual Telegram client as seen [here.](https://cdn.discordapp.com/attachments/377558555974434826/1063686246431457290/image.png)

### Actual behaviour

The files are not downloadable and do not properly show as they do in the actual Telegram client.

### Operating system

Windows 10

### Version of Kotatogram Desktop

1.4.8 x64

### Installation source

Static binary from official website

**Comment by Metalor696** [comment]
Hey mate, looking into this, I think this is when a message is posted to a topic - doesn't look like it's supported yet.

**Comment by EricKotato** [comment]
It will be resolved once Kotatogram is updated.
