### ISSUE TITLE
[Feature Request] Implement some features from 64Gram and ExteraGram on Android

### ISSUE THREAD

**Issue by Paras6408** [kotatogram/kotatogram-desktop#421]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Like custom emoji pack support , custom sticker size, rounded corners of stickers, show username instead of phone number, etc. etc.. etc...

### Describe alternatives you've considered

64Gram and ExteraGram

**Comment by ilya-fedin** [comment]
> custom sticker size

That's already supported

> show username instead of phone number

What do you mean?

**Comment by EricKotato** [comment]
Please create an issue per feature requested. Issues with multiple feature requests are harder to search and track (especially with "etc.").

Moreover, there may be some features that I won't implement at all or implement them differently. These things are also easier to track with separate issues.

**Comment by EricKotato** [comment]
BTW, if "custom emoji pack support" means Telegram feature implemented in TDesktop, then there is no need in this issue. See #420.
