### ISSUE TITLE
Premium Upload not working. 

### ISSUE THREAD

**Issue by markdavidb** [kotatogram/kotatogram-desktop#422]
### Steps to reproduce

The program limits you to a 2GB upload file even if you have a premium. 

### Expected behaviour

4GB upload possible if premium

### Actual behaviour

![Kotatogram_AdLJeiFDZ1](https://user-images.githubusercontent.com/63120933/214145591-4211c5b4-4344-4c3f-b7b4-bc436270077e.png)

### Operating system

win 11

### Version of Kotatogram Desktop

beta 1.4.9 TD 3.5.2

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
It will available when source code is updated. See #420.
