### ISSUE TITLE
[Feature Request] Ability to set custom telegram API_ID

### ISSUE THREAD

**Issue by eternal-sorrow** [kotatogram/kotatogram-desktop#424]
### Is your feature request related to a problem?

Right now you can't hide sponsored ads in channels, because then Kotatogram API_ID will be banned.

### Describe the solution you'd like

This can be circumvented by allowing users to enter their own API_ID and only then enabling an option to hide ads. This is done in Neko X on Android.

### Describe alternatives you've considered

None.

**Comment by RememberTheAir** [comment]
Kotatogram already supports it: https://t.me/s/kotatogram/169

**Comment by eternal-sorrow** [comment]
Ok, this is good. Then this feature request is about disabling sponsored ads when custom API_ID is used.

**Comment by RememberTheAir** [comment]
It's against Telegram's ToS, I don't think kotatogram wants to mess with them

**Comment by EricKotato** [comment]
>This can be circumvented by allowing users to enter their own API_ID and only then enabling an option to hide ads.

Even if option will be shown to those who use custom API ID, Kotatogram's API ID can be still in danger, because both Kotatogram API ID and violating feature are implemented in the same build.

This is not the risk I'm willing to take.
