### ISSUE TITLE
[Feature Request] Download content from restricted channel

### ISSUE THREAD

**Issue by roytam1** [kotatogram/kotatogram-desktop#429]
### Is your feature request related to a problem?

Some channels restricted saving contents from them, older kotatogram shows this dialog:
![image](https://user-images.githubusercontent.com/1192577/232180524-c98e86cb-6a4c-456d-a39f-2b589a6f2726.png)

while newer clients doesn't let me download:
![image](https://user-images.githubusercontent.com/1192577/232180613-07a08292-4241-4d60-ba3b-cfbfa40118cc.png)

### Describe the solution you'd like

I hope I can still able to download contents from such channels:
![image](https://user-images.githubusercontent.com/1192577/232180655-5c38c435-68e9-4e23-b149-d0a1977be6ff.png)

### Describe alternatives you've considered

maybe by ignoring channel's restrictions?

**Comment by EricKotato** [comment]
It violates Telegram API Terms of Services, so it won't be implemented.
