### ISSUE TITLE
[Feature Request] bypass text copying protection

### ISSUE THREAD

**Issue by drzraf** [kotatogram/kotatogram-desktop#430]
### Is your feature request related to a problem?

Some groups disable copying text.
When pressing "CTRL-C", a popup appears: _"Copying has been disabled by the admin"_

### Describe the solution you'd like

Override this limitation: My computer, my concern.

### Describe alternatives you've considered

.

**Comment by EricKotato** [comment]
This is against Telegram API Terms of Service, so it won't be implemented.

**Comment by drzraf** [comment]
The _Telegram API Terms_ (and whatever other API) doesn't bypass the control I have/pretend to have over my computer and running software. That's the whole point of FOSS (and of a fork).
Their API could pretend I must open the software exclusively after 12pm or reboot my computer at 1am or any other stupid clause, it would be the same.

Oh, and the law override illegal API terms (which usually ask for things they have no legal power to enforce)
They do that because it's not generally legal to issue unlawful ToS (until they're debunked in a court)

**Comment by EricKotato** [comment]
And this software uses Telegram API which means that some behavior may be unwanted for their service. Breaking their rules means that your client may lose access to API, and I'm not interested in fights with Telegram.

**Comment by drzraf** [comment]
What about an environment variable?
