### ISSUE TITLE
[Question] как поменять шрифт с open sans?

### ISSUE THREAD

**Issue by jucogjucogi** [kotatogram/kotatogram-desktop#432]
может я слепой, но все же
когда я меняю шрифт через json файл то он сразу ставится на дефолтный как только я запущу клиент, а в настройках я ничего не могу найти
помогите пожалуйста

**Comment by EricKotato** [comment]
А какая версия приложения?

**Comment by jucogjucogi** [comment]
![изображение](https://user-images.githubusercontent.com/113132803/236766936-3564f408-5e2e-40f8-ada6-4ccc3c06ed81.png)

**Comment by EricKotato** [comment]
Настройки > Настройки Kotatogram > Изменить шрифты приложения.

![](https://user-images.githubusercontent.com/2903496/236826425-0847eac9-21ba-4096-860b-15af7694ec0c.png)

Имейте в виду, что для того, чтобы шрифт работал, название должно быть написано такое же, как в системе (к примеру, Roboto Mono вместо RobotoMono.ttf). Однако ещё с 1.4.8 был добавлен список шрифтов, чтобы упростить задачу.

![](https://user-images.githubusercontent.com/2903496/236827069-bf0073a3-8bc1-4d59-8980-a42c4c666034.png)

**Comment by jucogjucogi** [comment]
спасибо, у меня на английском прога была и я не заметил
