### ISSUE TITLE
Message is not supported !!

### ISSUE THREAD

**Issue by Cykeek** [kotatogram/kotatogram-desktop#437]
### Steps to reproduce

![image](https://github.com/kotatogram/kotatogram-desktop/assets/70019075/35af33d4-5517-4625-b4d4-87fe7e549427)

### Expected behaviour

Some of the messages still show this unexpected warning of the old version of Kotatogram which I'm already in the beta version of it so please fix this in upcoming updates :)

### Actual behaviour

The message should show properly without respective versions of Kotatogram "_"

### Operating system

Windows 10

### Version of Kotatogram Desktop

1.4.9 beta x64 (TD 3.5.2)

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
See #420.
There's also patches-track branch, that you can build yourself.

**Comment by Cykeek** [comment]
sure no problem thanks for reply
