### ISSUE TITLE
[Feature Request] Adding downloads box at the bottom of the screen

### ISSUE THREAD

**Issue by Chapshan** [kotatogram/kotatogram-desktop#438]
### Is your feature request related to a problem?

yes. when downloading a file from one chat/group and then moving to another chat/group, there is no visibility on download progress.

### Describe the solution you'd like

same as in original telegram desktop app. when having downloads in progress that are not visible in screen, there is a dedicated box at the bottom that summarize all downloads state. when clicking on this box, it opens the list of all downloads and their current state.

### Describe alternatives you've considered

alternatively, a dedicated menu item to open that list can be a good solution also.

**Comment by EricKotato** [comment]
Since it's implemented in official TDesktop, it will be implemented in Kotatogram as soon as update comes out. See #420.
