### ISSUE TITLE
[Question] Update

### ISSUE THREAD

**Issue by K14Mua** [kotatogram/kotatogram-desktop#441]
Years passed, and there was still no client update. If you don’t want to do anything, just say so directly. Then we will all simply delete your client and go to use adequate analogues. How many more years will you have to wait until you give birth?

**Comment by ilya-fedin** [comment]
The work is ongoing, you can see new commits on the branches. It's just life happens and there's newer time to stabilize the code enough even for a beta version. If you're ready for instability, you can always build from source code.

**Comment by EricKotato** [comment]
The branch https://github.com/kotatogram/kotatogram-desktop/tree/patches-track-4.8.4 is going to be merged into dev and released to beta version, once I'll done with fixes.

If you wish to help with some of them, it would be much better than aggressively spamming same issue over and over again.

If you don't want to help, then there's either waiting, or using other apps (some of them I've even mentioned in #420).
