### ISSUE TITLE
Kotatogram cannot display some messages, but displays "This message is not supported by your version of Kotatogram Desktop. Please update to the latest version in Settings, or install it from https://kotatogram.github.io".

### ISSUE THREAD

**Issue by dreirund** [kotatogram/kotatogram-desktop#443]
### Steps to reproduce

1. Have someone write a Telegram-Message where the person [quotes a part of a previous message](https://telegram.org/blog/reply-revolution),
2. have Kotatogram display only "*This message is not supported by your version of Kotatogram Desktop. Please update to the latest version in Settings, or install it from https://kotatogram.github.io*", and not what the person.

### Expected behaviour

See the message.

### Actual behaviour

See

> *This message is not supported by your version of Kotatogram Desktop. Please update to the latest version in Settings, or install it from https://kotatogram.github.io*

### Operating system

Artix GNU/Linux (rolling release). No desktop environment -- xfwm4 as window manager.

### Version of Kotatogram Desktop

Local build from latest checkout from this git repository using [&nearr;&hairsp;this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kotatogram-desktop-git): `git describe --tags`: `k1.4.9-2-g52b300cb3`.

### Installation source

Local build from this git repository; using [&nearr;&hairsp;this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kotatogram-desktop-git) (Arch Linux [&nearr;&hairsp;AUR package "kotatogram-desktop-git"](https://aur.archlinux.org/packages/kotatogram-desktop-git)).

**Comment by dreirund** [comment]
[&nearr;&hairsp;Here](https://github.com/mautrix/telegram/commit/90a8583ad0f2b487269d634e8700175e6c58b6dc) is the implementation for mautrix-telegram that fixes the issue there.

**Comment by gawasvedraj** [comment]
wait for update

**Comment by dreirund** [comment]
> wait for update

When will it come?

**Comment by EricKotato** [comment]
#420

**Comment by dreirund** [comment]
> *#420*

:pray: :green_heart: thanks for (implicit, though :-() explanation!, that this is not an issue but a feature not yet implemented.

Regards!

**Comment by EricKotato** [comment]
Well, that's a feature which is implemented in newer TDesktop versions. There is a https://github.com/kotatogram/kotatogram-desktop/tree/patches-track-4.14 branch which contains not-yet-fixed code based on TD 4.14.

Also there are [development blogs](https://t.me/kotatogram_dev) and [test builds](https://t.me/KotatogramTestVersions) in Telegram if you're interested.
