### ISSUE TITLE
Drag and Drop File Limit for premium users

### ISSUE THREAD

**Issue by eldhoskariah** [kotatogram/kotatogram-desktop#447]
### Steps to reproduce

1.Select a file greater than 2 GB ,less than 4 GB 
2.Drag and drop it to any chat (in Telegram premium account )

### Expected behaviour

Premium user should be able to upload files upto 4 GB

### Actual behaviour

No files above 2 GB are allowed to drag drop and upload

### Operating system

Windows 11

### Version of Kotatogram Desktop

1.4.8 x64 TD 3.3

### Installation source

Static binary from official website

**Comment by EricKotato** [comment]
#420
