### ISSUE TITLE
[Question] When will there be an update?

### ISSUE THREAD

**Issue by K14Mua** [kotatogram/kotatogram-desktop#448]
How many more years do we have to wait for an update? IT'S BEEN TWO YEARS! It's impossible to release a working update in two years? What have you been doing for the last TWO YEARS!?

**Comment by EricKotato** [comment]
There is a https://github.com/kotatogram/kotatogram-desktop/tree/patches-track-4.14 branch which contains not-yet-fixed code based on TD 4.14.

Also there are [development blogs](https://t.me/kotatogram_dev) and [test builds](https://t.me/KotatogramTestVersions) in Telegram if you're interested.

And quoting #420:
> You may think that these issues will help the project in any way. In fact, they do the opposite: they create the noise. And without time and/or energy, the noise causes nothing more than stress.
