### ISSUE TITLE
Загрузка файлов для в linux

### ISSUE THREAD

**Issue by als-creator** [kotatogram/kotatogram-desktop#449]
Куда по [этому ману ](https://github.com/kotatogram/kotatogram-desktop/blob/dev/docs/building-linux.md) сохраняются файлы на диске? у меня 20гб оставшегося в корне места кончилось, не дойдя до конца, хотелось бы очистить до уровня как было.

**Comment by ilya-fedin** [comment]
в `docker buildx`

**Comment by als-creator** [comment]
12.6гб имиджей удалил, как то слишком много ради сборки одного пакета, подожду релиз

**Comment by ilya-fedin** [comment]
Там ведь не один пакет, а все нужные зависимости собираются

**Comment by als-creator** [comment]
понятно, но я со своим мобильным интернетом больше суток выкачивал те 80%, после которых все это прервалось и не ожидал что у меня еще и места на диске не хватит, диск я переразметил, 20гб добавил, но с такими объемами я лучше готовую сборку подожду

**Comment by ilya-fedin** [comment]
Если система имеет достаточно новые версии библиотек, можно использовать https://github.com/telegramdesktop/tdesktop/wiki/The-Packaged-Building-Mode. Инструкция предполагает наличия опыта по сборке софта и объясняет принцип действия нежели каждый шаг.
