### ISSUE TITLE
[Question]  kotatogram has a bann option?

### ISSUE THREAD

**Issue by ringo32** [kotatogram/kotatogram-desktop#453]
what i find on mobile is good can ban  a user main telegram doestn show it at  where you change user right... kotatogram idk see it also exactly?

**Comment by EricKotato** [comment]
Right click the user in members list, then "Restrict user" (or "Remove from group"). It's the same in TDesktop.
![](https://github.com/kotatogram/kotatogram-desktop/assets/2903496/908a484f-0045-4a9e-8db3-c0ac4ca20e71)

Restrict can be also done this way: Open group info > Manage group > Permissions > Exceptions > Add exception
