### ISSUE TITLE
[Question] What century will the update come out in?

### ISSUE THREAD

**Issue by K14Mua** [kotatogram/kotatogram-desktop#457]
Author, be honest, are you kidding us? When was the last fucking stable update? Dec 31, 2021. Two thousand fucking years ago. What is it now? It's been three years! What are you pulling? You could have written a NEW client from scratch in three years. You can't just update the old one. If you're not going to do anything, just say so. Say it honestly. Fuck the upgrade. And we'll stop writing to you. Why have you been lying to us for three years?

**Comment by ilya-fedin** [comment]
As far as I know @EricKotato works in a spare time on the project so there's just no time to stabilize updates given how frequently tdesktop updates. On other hand, code updates (not stable at all, not even beta quality) are done pretty frequently. The patches-wip branch is on 4.15.

**Comment by EricKotato** [comment]
> And we'll stop writing to you.

You can do it at any time, I don't know why do you keep writing that. You want to help? Then do it. Send the PR with bug fixes or updates, all info in #420. If not, just stop writing that. It's not productive, and will never be, and I've answered "why" many times.

**Comment by K14Mua** [comment]
It's unproductive to write a freaking update for 3 years! Naturally during this time the official client will be updated many times which requires even more work on the kotogram. And in the end we have what we have, three years have passed and the release is only getting farther away.

**Comment by ilya-fedin** [comment]
It's a common thing in free software world. Only projects that have hired developers due to interest in business usually have frequent updades. Everyone else usually have stable updates once in N years.

No one is lying here: the work is going, source code updates. You can build it. It's just not stable. No one advised frequent stable updates so I don't see a point in your complaints
