### ISSUE TITLE
[Feature Request] put the Kotatogram in the chocolatey package manager

### ISSUE THREAD

**Issue by HitaloSama** [kotatogram/kotatogram-desktop#48]
There is a very popular package manager in Windows called [chocolatey](https://chocolatey.org/) which makes it easy to install packages, uninstall and update, very complete and similar to apt, I would like Kotato to be available on it for the facilitation of updates and installation officially Telegram is already available on [chocolatey](https://chocolatey.org/), he’s just the official client.

**Comment by ilya-fedin** [comment]
> officially Telegram is already available on [chocolatey](https://chocolatey.org/)

Looks like this is not officially, it seems to be a third-party package :thinking:

**Comment by VaGNaroK** [comment]
I think it's wasting time, there are already binaries where you just have to download and install, (when there is a new version the client already updates) there is already the flatpak version that works in most distros and also has automatic updating, so it's kind of pointless create a third repository and maintain.

**Comment by RadRussianRus** [comment]
If it could be automated, it's fine, I think. You still serve same binary, but in different form, so there should be no problem with it.

**Comment by ilya-fedin** [comment]
> If it could be automated, it's fine, I think.

We'll have to build an additional binary without autoupdate. I don't think that Kotatogram in chocolatey is really needed.

> there is already the flatpak version

chocolatey is a windows package manager :(

**Comment by RadRussianRus** [comment]
> We'll have to build an additional binary without autoupdate.

I don't think it's the problem if binaries will be built on CI. Github Actions even has Chocolatey included in Windows container.
