### ISSUE TITLE
I can't hear other people and they can't hear me in a call

### ISSUE THREAD

**Issue by Angenios** [kotatogram/kotatogram-desktop#50]
### Steps to reproduce
**First method**:
1. Simply call someone
2. You'll find out you can't hear them (and they can't hear you?)

**Second method**:
1. Go to Call settings
2. Try "Test microphone"
3. You'll find out

### Expected behaviour
1.I should hear the other person and they should hear me.
2. In the Call settings, when I test the microphone I should see the bar lighting up.

### Actual behaviour
The microphone doesn't work, I've tried it from the settings too. But it is interesting to note that actually I can register voice messages and the microphone works fine. I've tried in the Call settings and I can confirm I've set the right audio source.

### Configuration
**Operating system:** 
Windows 10

**Version of Telegram Desktop:**
The latest version of Kotatogram Portable.

**Comment by Angenios** [comment]
Update: now I can hear people and they can hear me, but "Test microphone" in the Call settings still doesn't work.

**Comment by RadRussianRus** [comment]
Have you tested it on Telegram Desktop?
Also don't use term "latest", specify exact version. For now I will assume that you are on 1.3.5, so you need to compare it with Telegram Desktop 2.1.4.

**Comment by ilya-fedin** [comment]
> 2. In the Call settings, when I test the microphone I should see the bar lighting up.

This is upstream bug: https://github.com/telegramdesktop/tdesktop/issues/7296

> 1.I should hear the other person and they should hear me.

And looks like this is too: https://github.com/telegramdesktop/tdesktop/issues/7688

> I can register voice messages and the microphone works fine

Voice messages are recording with openal, while voice calls are working via libtgvoip.

**Comment by isaamos** [comment]
Same problem for me still

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
