### ISSUE TITLE
[Feature Request] User ID below online status in profile

### ISSUE THREAD

**Issue by watzon** [kotatogram/kotatogram-desktop#6]
It would be great to finally have this feature on desktop. Some mobile apps, specifically Plus Messenger, show a user's ID directly below their "last seen" in their profile. This would be enormously helpful since I am an admin in SpamWatch and need to get user ID's constantly.

Alternately it would be great to have the ability to write scripts in a language like Python or Lua that could basically turn the client into a userbot, but I'd settle for user IDs for now.

**Comment by RadRussianRus** [comment]
It is already done, but disabled by default. You can enable it in Settings > Kotatogram Settings > Show chat id.

**Comment by watzon** [comment]
Oh awesome. Thanks!

As far as scripting, is it something you'd consider? If so I can make a new issue.

**Comment by RadRussianRus** [comment]
Thought about that, but it's pretty big, so I can't say when.
