### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by WeFenFinit** [kotatogram/kotatogram-desktop#68]
### Is your feature request related to a problem?
Toxic group chat members
### Describe the solution you'd like
Mute in group chat on specific person
### Describe alternatives you've considered
Unfortunately, I did not find such solutions

**Comment by Neurotoxin001** [comment]
https://github.com/kotatogram/kotatogram-desktop/issues/17

**Comment by WeFenFinit** [comment]
Duplicate
