### ISSUE TITLE
[Feature Request] Change version name to 1.3.6 instead of 1.3.6-full for ebuild support

### ISSUE THREAD

**Issue by quisys** [kotatogram/kotatogram-desktop#70]
ebuild doesn't support letters in version names and thus errors out while configuring. a branch called just 1.3.6 would be much appreciated

**Comment by ilya-fedin** [comment]
What are you talking about?
![image](https://user-images.githubusercontent.com/17829319/85822404-45948880-b76a-11ea-9f11-4ca43f63c6ca.png)

**Comment by RadRussianRus** [comment]
It seems it's about full source code file name. It's the only place where it looks like 1.3.6-full.

**Comment by ilya-fedin** [comment]
> It seems it's about full source code file name. It's the only place where it looks like 1.3.6-full.

But that's not a branch name and the file name is the same as tdesktop uses

**Comment by ilya-fedin** [comment]
I don't believe that this is a problem for emerge in any way since there are existing at least three ebuild for kotatogram-desktop
