### ISSUE TITLE
gif and animated sticker stop playing

### ISSUE THREAD

**Issue by FinecoFinit** [kotatogram/kotatogram-desktop#73]
### Steps to reproduce
1. Enter chat with media disconnected (stickers, gifs)
2. Open menu with gifs and stickers

### Configuration
**Operating system: Windows 10 2004**

**Version of Telegram Desktop: 1.3.6 beta**

**Comment by ilya-fedin** [comment]
@RadRussianRus I don't think there's a reason to have that issue open
