### ISSUE TITLE
Антивирус встроенный в систему стал срабатывать на апдейтер

### ISSUE THREAD

**Issue by f242** [kotatogram/kotatogram-desktop#76]
![image](https://user-images.githubusercontent.com/10371194/85923903-7cb48800-b897-11ea-8bfa-906419f2b1ba.png)
На апдейтер оригинального клиента не ругается

**Comment by RadRussianRus** [comment]
Это случалось и с оригинальным клиентом. Сейчас такого не происходит из-за цифровой подписи, которую мне не получить.
