### ISSUE TITLE
[Feature Request] Выбор размера панели с эмодзи, когда включено "не отображать панель эмодзи при наведении"

### ISSUE THREAD

**Issue by Neurotoxin001** [kotatogram/kotatogram-desktop#79]
Если отображение эмодзи панели при наведении отключено, открыть её можно **только кликом и в большом виде** сбоку, предлагаю сделать настройку с выбором, какая будет открываться при клике — маленькая или большая

Маленькая:
![image](https://user-images.githubusercontent.com/39812401/86476696-b3831600-bd4f-11ea-9c48-693416e08e97.png)

Большая:
![image](https://user-images.githubusercontent.com/39812401/86476722-bed64180-bd4f-11ea-9b98-22733e1999f8.png)

**Comment by ilya-fedin** [comment]
Я за то, чтобы по первому клику открывалась маленькая, а по следующему - большая.

**Comment by RadRussianRus** [comment]
Я пока сделал, чтобы маленькая открывалась по правому клику, если отключено по наведению. Саму настройку дорабатывать буду позже.
