### ISSUE TITLE
[WINDOWS] Malware in updater.exe?

### ISSUE THREAD

**Issue by aTomicTurnip** [kotatogram/kotatogram-desktop#80]
I was installing the latest beta and my antivirus reported that the updater was infected with a **Trojan:Wacatac.B!ml**
Can someone dig in it please? I was using the portable version. Can't add screenshots because I deleted the folder an the antivirus has no log related to that, don't know why.

**Comment by RadRussianRus** [comment]
It's false positive. Original TDesktop updater doesn't have this problem only because it's signed, but had problems earlier.
