### ISSUE TITLE
[Feature Request] Добавить кнопку "ограничить пользователя" при клике на него в чате группы

### ISSUE THREAD

**Issue by Neurotoxin001** [kotatogram/kotatogram-desktop#82]
Сейчас эта кнопка есть только в недавних действиях:
![image](https://user-images.githubusercontent.com/39812401/86511366-1c769680-be01-11ea-91b5-d82ada8bb8bc.png)

И чтобы ограничить пользователя, приходится заходить в список пользователей, было бы удобно, если бы эта кнопка была и в основном окне чата:
![image](https://user-images.githubusercontent.com/39812401/86511371-24363b00-be01-11ea-8ab1-18f25cf638f0.png)

**Comment by RadRussianRus** [comment]
К слову, в TDesktop в списке участников по правому клику можно ограничить пользователя.
