### ISSUE TITLE
macOS 10.13.6 crash

### ISSUE THREAD

**Issue by dayfuaim** [kotatogram/kotatogram-desktop#83]
При запуске на macOS 10.13.6 получаю crash report:

```
...
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Kotatogram.app/Contents/MacOS/../Frameworks/libopenal.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
...
```

Видимо, собирали уже в Catalina.

Исправьте, пожалуйста.

**Comment by ilya-fedin** [comment]
А как исправить? :thinking:

**Comment by dayfuaim** [comment]
@ilya-fedin Ну, я думаю, что собирать нужно в окружении и библиотеками, соответствующими, скажем, macOS 10.12+.
Может быть, к экшне для сборки это нужно указать (предположение).

**Comment by ilya-fedin** [comment]
Нету там ничего, кроме 10.15: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by dayfuaim** [comment]
@ilya-fedin Мдя... Выглядит как "печалька". Но не у всех же стоит последняя Каталина.
А как у апстрима сделано?
Я имею в виду обычный Телеграм. Он же работает на 10.10, и на 10.12, 
и на 10.13 (все проверены на личном опыте, по пути обновления системы).

**Comment by ilya-fedin** [comment]
> А как у апстрима сделано?

У разраба тдесктотпа макбук, он на нем и компилит

**Comment by dayfuaim** [comment]
@ilya-fedin Ясно, это не _как_, это – _на чём_. ;)
Видимо, нужно что-то типа вот этого: https://github.com/telegramdesktop/tdesktop/actions/runs/161774026/workflow
(это Маковский action, которым собираются пакеты)
И полагаю, что нужны строки 53 и 54, а также строка 468.

**Comment by ilya-fedin** [comment]
> это Маковский action, которым собираются пакеты

Это маковский экшен, которым собирается debug build для CI, релизные билды разрабом тдесткопа собираются полностью вручную

**Comment by ilya-fedin** [comment]
Проблема в том, что разраб тдесктопа использует в своих релизных билдах LTO, который занимает несколько часов и очень много ОЗУ, поэтому мы не можем юзать его метод для сборки релизных билдов.
Мы ставим зависимости из brew, которые как раз, наверное, собраны только под Catalina.
Но, собственно, у нас другого выхода и нет.

**Comment by dayfuaim** [comment]
Вас понял.

ОК, подождём, пока у меня заведётся Каталина. Уже очень скоро, я думаю.

Тогда закрываю баг, "за отсутствием состава преступления". :D
