### ISSUE TITLE
Сделать меньше ограничение по ширине и высоте окна

### ISSUE THREAD

**Issue by mpodshivalin** [kotatogram/kotatogram-desktop#84]
### Is your feature request related to a problem?
На мобильных устройствах с Linux, к примеру, PinePhone, на удивление Kotatogram работает весьма прилично за исключением одной важной проблемы - он немного не помещается по ширине и по высоте (по высоте видна проблема если открыть клавиатуру)
![list](https://user-images.githubusercontent.com/16121630/86639476-9c5b5700-bfe1-11ea-912e-f84dff193fb1.jpg)
![chat](https://user-images.githubusercontent.com/16121630/86639491-9feede00-bfe1-11ea-93f5-44ce1dab5511.jpg)
![chat-with-keyboard](https://user-images.githubusercontent.com/16121630/86639495-a2513800-bfe1-11ea-8a32-3eccf4180742.jpg)

В остальном - скроллинг пальцем, фото, просмотр видео работают, это по сути главная проблема которая не даёт использовать клиент Telegram на телефоне.

### Describe the solution you'd like

Разрешение экрана телефона 720х1440 с HiDPI, т.е. минимальная ширина должна быть 360, а высота, с учётом клавиатуры, в районе 400 (т.к. клавиатуры бывают разные)

### Describe alternatives you've considered
Сделать опцию Default Interface Scale 75%, но это вариант хуже)

### Additional context
Ещё идеально было бы сделать возможность скрыть папки, т.к. на десктопе они нужны, а на мобильной версии - нет.

Баг в оригинальном клиенте https://github.com/telegramdesktop/tdesktop/issues/8058

**Comment by ilya-fedin** [comment]
Ну, собственно, проблема та же, что и в оригинальном клиенте - тут нужен перепил контролов, чтоб умещалось в более маленькие экраны. Вряд ли мы будем это делать, разве что кто-то занесет.

**Comment by mpodshivalin** [comment]
Хм, а если как "запасной вариант" - вот эта настройка
![image](https://user-images.githubusercontent.com/16121630/86806016-1ee72380-c081-11ea-9eef-36cd74e39c93.png)
сейчас увеличивает пропорционально полностью весь интерфейс. Нельзя ли сделать 75%, чтобы пропорционально уменьшилось?))

**Comment by ilya-fedin** [comment]
Ну тогда нужна графика с масштабом 0.75, а нам негде взяять векткорный оригинал, чтобы сделать её.

**Comment by mpodshivalin** [comment]
А что за графика? Если есть возможность, пришлите ссылку (код) про что речь идёт - если это, условно говоря, картинки, то может я например попробую их подогнать - графика 2.5 же есть)

**Comment by ilya-fedin** [comment]
Иконки. Ну даже если и подогнать, они все равно потеряют в качестве.

> графика 2.5 же есть

сейчас проверил - только 2x и 3x графика есть :thinking: 

А вы уже пробовали 0.75 масштаб на практике, оно хоть нормально работает?

**Comment by mpodshivalin** [comment]
Проверить прежде чем это делать конечно хорошая идея :) Но как запустить с маштабом 0.75? Для этого можно какой-то флаг поставить, или потребуется кастомную версию сделать? Если скажете где что поменять, проверю.
Да, в качестве похоже потеряет, но это значительно лучше, чем ничего))

**Comment by ilya-fedin** [comment]
> Но как запустить с маштабом 0.75?

Аргумент `-scale 0.75`

**Comment by mpodshivalin** [comment]
А всё нормально, если со --scale 75 запустить, то всё помещается, клавиатура открывается, более того этот параметр даже сохраняется и клиент открывается в последующие разы уже в нормальном виде :) Текст конечно мелкий но перепил контролов наверное в оригинальном клиенте авторами только если делать) 
Так хотя бы работает, причём неплохо ) Cпасибо!

**Comment by mpodshivalin** [comment]
Если, кстати, в Kotatogram Settings сделать настройку не только самого шрифта, а его размера, то это вообще решило бы проблему, но сказать то легко, вопрос насколько это сложно сделать)

**Comment by ilya-fedin** [comment]
У тдесктопа там кастомный рендеринг с выдранным кодом из Qt и использоваанием приватных API, при изменении размера шрифта, скорее всего, всё поедет.

**Comment by mpodshivalin** [comment]
Вот так всегда, думаешь "Ну, у Telegram то точно всё с точки зрения техники идеально сделано", а в реальности кастомный рендеринг с использованием приватных API :)
Но в целом, сама проблема то решена )

**Comment by ilya-fedin** [comment]
> "Ну, у Telegram то точно всё с точки зрения техники идеально сделано"

Коду официальных клиентов Telegram даже бог не поможет :see_no_evil: :see_no_evil: :see_no_evil:
