### ISSUE TITLE
"Emoji panel on hover" ignored when inside the scheduled messages screen

### ISSUE THREAD

**Issue by RememberTheAir** [kotatogram/kotatogram-desktop#86]
### Steps to reproduce
1. disable "Emoji panel on hover" option from kotatogram settings
2. schedule a message in a chat
3. go inside the scheduled messages screen
4. hover on the emoji icon

### Expected behaviour
The emoji panel doesn't pop up because "Emoji panel on hover" is disabled

### Actual behaviour
The emoji panel pops up

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.7

**Comment by RadRussianRus** [comment]
Will be fixed in next version.
