### ISSUE TITLE
[Feature Request] Ability to view user's chat history

### ISSUE THREAD

**Issue by watzon** [kotatogram/kotatogram-desktop#9]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Mobile apps like Plus give the ability to long press on a user's profile photo to long press on a user's profile photo and select a "Show user messages" option to show all of their message history in the current group. This is really helpful as an admin especially since it allows you to check if someone is join spamming, or if a particular user has an ongoing history of a specific behavior.

### Describe alternatives you've considered
Currently I just have to open up Plus Messenger on my phone any time I want to check

### Additional context
N/A

**Comment by RadRussianRus** [comment]
Know this feature from Telegram X. Actually it's a shortcut for searching messages by user, but since this works only for users in this group, it would be handy.

**Comment by watzon** [comment]
Yeah it would be really nice to have. Very helpful for admins.

**Comment by RadRussianRus** [comment]
The feature was added in 1.3.

Right click in members list > User messages
or
Right click on user message > User messages

**Comment by Neurotoxin001** [comment]
Предлагаю добавить кнопку "сообщения пользователя" ещё и в "недавние действия" (туда же, где и "удалить из группы/ограничить пользователя" сейчас), так как бывает полезно посмотреть все оставшиеся посты человека, который, например, удалил свой пост, или когда кастомный анти-спам бот удаляет его посты. Чтобы удалить все оставшиеся.

Сейчас приходится это делать вручную.
