### ISSUE TITLE
[Feature Request] Option to hide the title bar

### ISSUE THREAD

**Issue by Blacksuan19** [kotatogram/kotatogram-desktop#91]
### Is your feature request related to a problem?
I use a tiling WM and it doesn't have a title bar for apps, 
kotato uses its own title bar and does not follow the system settings

### Describe the solution you'd like
An option to hide the title bar 

### Describe alternatives you've considered
None

### Additional context
Screenshot of title bar
![image](https://user-images.githubusercontent.com/10248473/88029975-418f3700-cb6d-11ea-8897-f20ab510be94.png)

**Comment by ilya-fedin** [comment]
The option exists and inherited from tdesktop

**Comment by Blacksuan19** [comment]
I don't see the option anywhere, someone said it was in system integration under advanced settings but I don't have that option although he was running Wayland while am running  X11, can that be a problem?

here is my advanced settings page, even in stock telegram I don't have the option

kotatogram 
![image](https://user-images.githubusercontent.com/10248473/88144320-529e7d80-cc2b-11ea-9e0c-990b90fb0808.png)

stock telegram
![image](https://user-images.githubusercontent.com/10248473/88144578-b9239b80-cc2b-11ea-8bf7-976a86f4e55d.png)

**Comment by ilya-fedin** [comment]
tdesktop developer added the option to tray settings, therefore it is not shown when the tray is not available

**Comment by Blacksuan19** [comment]
Thank you!
after installing stalonetray the relaunching the app, the option was there and I was able to hide it
closing this now
