### ISSUE TITLE
[Feature Request] Option to uncheck “Notify all members” by default

### ISSUE THREAD

**Issue by Brawaru** [kotatogram/kotatogram-desktop#93]
### Is your feature request related to a problem?

Most times I pinned messages, I never had “Notify all members” checked, because I don't really pin anything important that worth mentioning bunch of people, but this option is always checked by default and miss it one time — expect to be roasted or canceled for mentioning everyone for the rest of your life. It's [like Discord](https://youtu.be/o-KuOecz1Ks).

### Describe the solution you'd like

I used [`telegram-desktop-udf-patched`](https://aur.archlinux.org/packages/telegram-desktop-udf-patched/) fork which had [patch to invert this behavior](https://aur.archlinux.org/cgit/aur.git/tree/always_pin_without_notify.patch?h=telegram-desktop-udf-patched) and uncheck this option by default.

### Describe alternatives you've considered

- **Unchecking it manually** (what I do now), but this is very risky as described above and no [motivation quotes](https://www.virgin.com/richard-branson/my-top-10-quotes-risk) can calm me down on taking it every time.
- **Not pinning messages**. This is highly ineffective, what I'm gonna do? Forward message a thousand times?

### Additional context

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/88751163-3c3f7700-d181-11ea-987c-43139467f0a2.png" alt="Screenshot of dialog with “Notify all members” option unchecked">
</p>
<p align=center>Picture of my dream 💫😍</p>

**Comment by RadRussianRus** [comment]
I've implemented it locally, will be shipped in next version.
