### ISSUE TITLE
Opening media while Kotatogram is full screen on MacOS leaves black workspace

### ISSUE THREAD

**Issue by rodneyrod** [kotatogram/kotatogram-desktop#94]
### Steps to reproduce
1. Open Kotatogram on MacOS and make full screen
2. Open any media, this will open in another full screen workspace
3. When you close the media that's open, it goes to a black screen

### Expected behaviour
The media preview full screen page will close and go back to the chat in Kotatogram 

### Actual behaviour
Media preview full screen page stays open on a black page

### Configuration
**Operating system:**
MacOS 10.15.6

**Version of Telegram Desktop:**
1.3.8 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Can you record some screencast representing the issue? I can't understand what are you talking about...

**Comment by rodneyrod** [comment]
Don't have the ability to screencast, but I'll try and demonstrate what I mean.

This is what a normal photo preview looks on MacOS when Kotatogram is a window:
![image](https://user-images.githubusercontent.com/5110437/89743229-75160f00-dae4-11ea-9ea2-0a8ca35749ab.png)

This is fine and the photo can be opened and closed without issue.

When you do the same thing in fullscreen mode, it does the same thing at first:
![image](https://user-images.githubusercontent.com/5110437/89743249-a1319000-dae4-11ea-834f-06a3b75ad67f.png)

But when you close it, you get a black fullscreen window that you can't close even with command + w
![image](https://user-images.githubusercontent.com/5110437/89743266-ccb47a80-dae4-11ea-8180-00805b8d82fe.png)

And the black window shows up in mission control is this:
![image](https://user-images.githubusercontent.com/5110437/89743284-fe2d4600-dae4-11ea-8aac-ab190ed51b77.png)

I've also noticed that you can quit Kotatogram in windowed mode fine with command + Q, but when it's in fullscreen mode it only closes the active window at first but then quits on the second attempt. This even happens when selecting quit from the top menubar.

**Comment by ilya-fedin** [comment]
Hmm, seems to be https://bugreports.qt.io/browse/QTBUG-46701, but it is weird if this is not reproducible on tdesktop... :thinking:

**Comment by rodneyrod** [comment]
Just saw a swathe of Qt updates come in, happy to test this again once the new release is ready for testing.

**Comment by RadRussianRus** [comment]
@rodneyrod Have you tested it on latest Kotatogram 1.4 version?

**Comment by rodneyrod** [comment]
Tested and working fine, thanks for fixing this!
