### ISSUE TITLE
Bug caused after picture is sent.

### ISSUE THREAD

**Issue by Mazeorz** [kotatogram/kotatogram-desktop#95]
macOS

After sending the picture, the picture displayed normally in the computer terminal.

But on the mobile app, it is too vague and white.

There is no such problem when sending pictures with Telegram.

![image](https://user-images.githubusercontent.com/67795943/90766612-69b1b780-e31e-11ea-8ac7-8a3f3eb7183b.png)

**Comment by ilya-fedin** [comment]
It looks ok to me
